### ISSUE TITLE
Questions: Fire & forget event broadcasting 

### ISSUE THREAD

**Issue by pierre-roudaut-cko** [jamesmh/coravel#103]
Hi,

1. thanks to the use of the discard operator, I have been able to use event broadcast in a "fire & forget" manner. Is this the recommended way to achieve it? 

2. In this case, `DoThis` and `DoThat` are performed subsequently. Am I guaranteed that this is the predictable behavior or could those listeners be ran in parallel?

```c#
registration
        .Register<ItemCreated>()
        .Subscribe<DoThis>()
        .Subscribe<DoThat>();
```

```c#
_ = dispatcher.Broadcast(new ItemCreated(item.Id));
// return to the caller directly
```

I couldn't find answers related to this topic in the documentation...

Thanks a lot for your help (and for this really cool framework 🙏 )

**Comment by jamesmh** [comment]
I wouldn't recommend that since `Broadcast` is async and as a best practice you should always await async methods.

In this case, to do a fire-and-forget, you can do this:

https://docs.coravel.net/Queuing/#queuing-an-event-broadcast

**Comment by jamesmh** [comment]
For #2, assuming you are awaiting all your async operations, then they should be executed one at a time. 👍

**Comment by pierre-roudaut-cko** [comment]
Ok, that clears it out. Thanks for the replies 👍
