### ISSUE TITLE
Configurable Coravel's dashboard URL

### ISSUE THREAD

**Issue by XardasLord** [jamesmh/coravel#104]
I would like to change the URL of the Coravel's Dashboard

**Comment by jamesmh** [comment]
Not sure if that's even possible given that the routes are using razor lib view components...?

**Comment by jamesmh** [comment]
Sry this should be on https://github.com/jamesmh/coravelpro

**Comment by jamesmh** [comment]
See https://github.com/jamesmh/coravelpro/issues/10
