### ISSUE TITLE
How to manage the tasks? something like GetTasks, Remove, Disable, Clear?

### ISSUE THREAD

**Issue by funwaywang** [jamesmh/coravel#106]
thanks for the great job, It's beautiful for me.
I have read the official manual on docs.coravel.net ,
So I know how to add schedule task, 
but, Is there a way to manage tasks?
just like search the tasks list, or remove a task, or disabled it?

**Describe the solution you'd like**
I expect maybe some methods like: GetTasks, RemoveTask, DisableTask, ClearTasks...

**Describe alternatives you've considered**

I think it is very possible, they already exist and I don't know. If so, I hope you can tell me. Thank you very much.

**Comment by jamesmh** [comment]
There's no public API to do those kinds of things since the scheduler is designed to deal with re-occurring schedules vs dynamic schedules
