### ISSUE TITLE
Coravel Mail and .net core 3.0 support

### ISSUE THREAD

**Issue by yakine-dev** [jamesmh/coravel#115]
**Describe the bug**
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment' from assembly 'Microsoft.AspNetCore.Hosting, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
when using asp.net core 3.0 i cant add the email feature

**Affected Coravel Feature**
Mail

**Expected behaviour**
Add Mail

**Comment by jamesmh** [comment]
Yes, so .NET Core 3 introduced quite a few breaking changes from 2.1 onward.

This one, in particular, can be found [here in the .NET Core 3 migration docs](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references).

Coravel (Mailer in particular) uses some of those "obsolete" packages. Great.

Except, removing those packages means Coravel Mailer **won't** work with any previous version of .NET Core 🙃

So the question is: Should Coravel (Mailer in particular for this issue) support **only** 3.0 and onward? Or support 2.0, 2.1, 2.2 but **not** 3.0 (yet) ?

It's not a simple answer! I'm feeling like I should wait until 3.1 because that is a long-term release.

🤷‍♂️

**Comment by dmitrydvm** [comment]
Hi,
3.1 is released :-)

**Comment by vitalyhermonlabs** [comment]
I use core 3.1 and Coravel Mailer anyway requires obsolete IHostingEnvironment and is not working

**Comment by jamesmh** [comment]
Yes the mailer doesn't support .NET Core 3.0+ plus yet.

**Comment by vitalyhermonlabs** [comment]
it's a pity, do you know when approximately the mailer will support .NET Core 3.0+?
Thank you

**Comment by jamesmh** [comment]
Soon 😉

**Comment by mnowacki** [comment]
Any news when mailer will support .Net Core 3.0+? :pray:

**Comment by jamesmh** [comment]
Sorry, started working on it but .NET Core 3 made some fundamental changes that directly impact the mailer. Will post when there's more news.

**Comment by tolbxela** [comment]
Any news on mailer will support .Net Core 3.0+? 🙏

Do you need some contributing support towards?

**Comment by jamesmh** [comment]
I'm not sure...

Migration is fine and straightforward, expect [with this file.](https://github.com/jamesmh/coravel/blob/master/Src/Coravel.Mailer/Mail/Renderers/RazorRendererFactory.cs)

If anyone wants to take crack at it then yes, that would be helpful 😀

**Comment by BarFoo** [comment]
I've had a go at trying to resolve this locally for a 3.1 project, so I can submit a pull request but I am faced with the following:

Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IWebHostEnvironment' while attempting to activate 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptionsSetup'.

I can't find which services to register so IWebHostEnvironment can be resolved. Or even how to add a singleton of this. 

Anyone have any ideas?

**Comment by BarFoo** [comment]
Ok I came up with a somewhat messy and bizarre workaround, which works only for 3.0+. It is so messy I don't feel comfortable with a pull request.

Anyway here is how I've got it working for 3.0+. Please note you'll have to build from the Mailer source yourself to get this working, and a project reference..

**1. Remove nuget packages**

```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.App" />
```

**2. Add Nuget packages**

```
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.3" />
 <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.3" />
```

**3. IWebHostEnvironment workaround**

Add a custom model that inherits from IWebHostEnvironment.

```
public class MailWebHostEnvironment : IWebHostEnvironment
{
    public IFileProvider WebRootFileProvider { get; set; }
    public string WebRootPath { get; set; }
    public string EnvironmentName { get; set; }
    public string ApplicationName { get; set; }
    public string ContentRootPath { get; set; }
    public IFileProvider ContentRootFileProvider { get; set; }
}
```

** 4. Update Mail/RazorRenderFactory.cs**

```
public static RazorRenderer MakeInstance(IConfiguration config)
{
    var services = new ServiceCollection();
    services.AddSingleton<IConfiguration>(config);
    var applicationEnvironment = PlatformServices.Default.Application;
    services.AddSingleton(applicationEnvironment);

    var appDirectory = Directory.GetCurrentDirectory();
            
    var environment = new MailWebHostEnvironment
    {
        ApplicationName = Assembly.GetEntryAssembly().GetName().Name
    };

    services.AddSingleton<IWebHostEnvironment>(environment);

    services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();

    var diagnosticListener = new DiagnosticListener("Microsoft.AspNetCore");
    services.AddSingleton<DiagnosticSource>(diagnosticListener);
    services.AddSingleton<DiagnosticListener>(diagnosticListener);

    services.AddLogging();
    services.AddRazorPages().AddRazorRuntimeCompilation();
            
    services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
    {
        options.FileProviders.Clear();
        options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
    });

    services.AddSingleton<RazorRenderer>();

    var provider = services.BuildServiceProvider();
    return provider.GetRequiredService<RazorRenderer>();
}
```

**Comment by jamesmh** [comment]
Thanks @BarFoo. I'll check this out some time and see what happens. I'm at a spot where everything compiles, but at runtime things blow-up 🤷‍♂️ 

I know devs in private businesses who are facing this same issue 😥 Sad.

**Comment by BarFoo** [comment]
@jamesmh My above posted solution absolutely works for 3.0+ at runtime. Perhaps you could add an optional parameter to the MakeInstance method, perhaps an enum to set compatability mode and have it default it to 2+. This will allow devs to override it in their Startup/DI registration, so if they set 3 it will use the logic I have above, or use the existing logic for 2.

**Comment by jamesmh** [comment]
So, @BarFoo...I couldn't get your solution to work. However, I figure something else out....

This seems to work in Coravel.Mailer.3.0.0-preview1

Please, everyone, give it a try and let me know if everything seems to work with .NET Core 3.1. Worked for me, but you never know. I had to make a significant change to how the view compilation was happening.

Took a lot of work! Hopefully this pans out 👍

**Comment by MathavanN** [comment]
@jamesmh Is it possible to Validate SMTP connection without sending mail
Im using coravel.mailer-3.0.0-preview1

**Comment by jamesmh** [comment]
No, that would require an additional feature. You can open a new issue 👍

**Comment by jamesmh** [comment]
So version 3.0.0 is out. Haven't heard about an issues - so closing this 👍
