### ISSUE TITLE
Can't install package when project targets .NET framework 4.7.2???

### ISSUE THREAD

**Issue by tjahnks23** [jamesmh/coravel#121]
Error when trying to install package: Could not install package 'Coravel 2.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

**Comment by jamesmh** [comment]
Coravel only supports .NET Core and not .NET Framework.
