### ISSUE TITLE
Queue Count

### ISSUE THREAD

**Issue by andrew-williams-cko** [jamesmh/coravel#122]
**The problem**
As part of an acceptance test, I need a way to determine whether all tasks within the queue have already been consumed or not before moving on to the next step i.e. checking the side-effects of what the listener has done given the event in the queue.

**Describe the solution you'd like**
The simplest possible solution, expose `_task.Count` as `IQueue.Count`

**Describe alternatives you've considered**
Considered making Queue as a component you can attach listeners to, so you can listen to events being added and removed etc. but seems overkill for this simple use case.

**Comment by jamesmh** [comment]
That sounds more like an integration test, in which case I would expect it to be more appropriate to wait for the queue to run and then make the check. 

You can configure how long the queue waits to run each time: https://docs.coravel.net/Queuing/#adjusting-the-consummation-delay

Mocking libraries (like Moq) have ways to check if certain methods have been executed within the test's scope. That way you don't need to fiddle around with internal details of business/app code to test them.

**Comment by andrew-williams-cko** [comment]
I guess you're right, it's probably leaking implementation detail to the wrong level - it is at an integration level rather. It always seems unreliable to use some kind of `wait` and `retry` mechanisms though, rather than exposing something for the sake of the test.

What about for metrics purposes? i.e. I want to know how well my consumers are handling the number of events in the queue.

**Comment by jamesmh** [comment]
I think in this case emitting an event(s) would probably work best... I'll consider this a new feature.

**Comment by jamesmh** [comment]
I think this will cover this issue. Let me know if not 👍

https://docs.coravel.net/Queuing/#metrics
