### ISSUE TITLE
No service for type X has been registered.'

### ISSUE THREAD

**Issue by bpollardFlow** [jamesmh/coravel#123]
**Describe the bug**
I am creating a new .NET Core project from scratch to use Coravel Pro.  I have attempted this in both .NET Core 3 and 2.2 with the same result.  Whenever I hit app.UseCoravelPro(); i get 

No service for type 'HoloNetCommand.FlowAutoDotComContext' has been registered.'

I really want to use this tool, but I cannot get past this.  Can you help?

**Comment by jamesmh** [comment]
Sure! What does your Startup.cs method ConfigureServices look like?

**Comment by bpollardFlow** [comment]
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseCoravelPro();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

**Comment by bpollardFlow** [comment]
services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddCoravelPro(typeof(FlowAutoDotComContext));

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

**Comment by bpollardFlow** [comment]
I figured it out.  I was missing a good bit of stuff in my startup and program classes.

**Comment by bpollardFlow** [comment]
Thanks!

**Comment by jamesmh** [comment]
Great! Let me know if you have any more questions or issues. Coravel Pro has its own repo if you need to create some future issues 👍

https://github.com/jamesmh/coravelpro
