### ISSUE TITLE
Invocable arguments?

### ISSUE THREAD

**Issue by lloydjatkinson** [jamesmh/coravel#128]
Hi,

Not sure if this is more of a feature request or a question but anyway. With Quartz.NET and Hangfire, arguments can be passed to jobs. (https://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/more-about-jobs.html)

How would we achieve something similar to this with Coravel?  A use case for this would be a "daily email report" type job, except the invocable is registered twice but with a different argument, perhaps indicating which mailing list to use, and one mailing list is for 8AM while the other is 9AM.

**Comment by jamesmh** [comment]
Off the top of my head....

```c#
services.AddTransient<DailyEmailReportInvocable>(p => new DailyEmailReportInvocable("8am"));
services.AddTransient<DailyEmailReportInvocable>(p => new DailyEmailReportInvocable("9am"));
```

Something like that. You can instruct the service container to use those lambda methods when instantiating your invocable classes. You can inject whatever you want (like you were asking for).

If you need access to another service from DI, you can do something like:

```c#
services.AddTransient<DailyEmailReportInvocable>(p => new DailyEmailReportInvocable(p.GetService<SomeOtherType>(), "8am"));
```

Again, off the top of my head. Might be some slight variation on the real method names etc. 🙃

**Comment by jamesmh** [comment]
You can take a look at this sample:

https://github.com/jamesmh/coravel/blob/master/Samples/QueueWithCancellationTokens/Controllers/QueueController.cs

That's queuing an invocable class.

Let me know if you have any questions?

**Comment by jamesmh** [comment]
So, this suggestion I made:
```c#
scheduler.ScheduleAsync(async () => {
    var job = new SomeInvocable("MailList1");
    await job.Invoke();
}).DailyAtHour(8);
```

Potentially, I could add a new method on the scheduler:

```c#
scheduler
    .ScheduleWithParams<SomeInvocable>("MailList1")
   .DailyAtHour(8);
```

And that would pass the parameters into the Invocable via the contructor... or even use property injection (which might work better with expressions...).

Anyways, this would make a nice addition like you suggested 👌

**Comment by lloydjatkinson** [comment]
Thank you for taking a look :)

**Comment by schmitch** [comment]
actually passing it via the instructor wouldn't be that good, since it will make it harder to register the invocable.

**Comment by jamesmh** [comment]
FYI I'm thinking of preferring a property injection type approach. 

So instead of this:

```c#
scheduler
    .ScheduleWithParams<SomeInvocable>("MailList1")
   .DailyAtHour(8);
```

It would be like this:

```c#
scheduler
    .ScheduleWithParams<SomeInvocable>(i => i.MailListName = "MailList1")
   .DailyAtHour(8);
```

**Why not constructor injection?**

Because invocables are already configured to work via the DI container with .NET Core.

Using the constructor injection method means that invocable cannot use the DI container anymore (since Coravel now needs to manually instantiate this invocable).

With property injection, or at least allowing an extra feature that set whatever properties you need, avoids this issue and you gain the best of both worlds.

**Comment by lloydjatkinson** [comment]
Constructor injection is the best way.

**Comment by jamesmh** [comment]
Why do you think so @lloydjatkinson ?

**Comment by jamesmh** [comment]
Done by @Blinke.

See docs -> https://docs.coravel.net/Scheduler/#scheduling-with-additional-parameters
