### ISSUE TITLE
Minor Spelling Issue in Readme

### ISSUE THREAD

**Issue by KSib** [jamesmh/coravel#131]
**Describe the bug**
Minor issue in docs: "copywrite" instead of "copyright" in DocsV2/docs/Mailing/README.md

**Affected Coravel Feature**
Documentation

**Expected behaviour**
Correct spelling

**Comment by jamesmh** [comment]
Did you want to issue a PR for that?

**Comment by KSib** [comment]
I thought I did and realized I didn't do it correctly. (Just now learning
git, previously only used svn and tfs) if it's not done before I get home
this weekend then I'll take another swing at it.

**Comment by jamesmh** [comment]
Awesome - no rush btw. Thanks!

**Comment by jamesmh** [comment]
Fixed
