### ISSUE TITLE
Missed Broadcast Events

### ISSUE THREAD

**Issue by akytsun** [jamesmh/coravel#132]
**Describe the bug**
In my net core 2.2 web api project I'm using ` _queue.QueueBroadcast` to publish events.
I've added logging to my `IListener<MyEvent>` implementation in `HandleAsync` method.
ConsummationDelay was set to 15.
Every time if I trigger api call which trigger `_queue.QueueBroadcast(new MyEvent())` one by one, only one of published events will be really consumed and fired. Where Coravel can miss others I don't know. Any ideas?

**Affected Coravel Feature**
Queuing, Event Broadcasting

**Expected behaviour**
HandleAsync should fire for each published events at max ConsummationDelay time

**Comment by jamesmh** [comment]
Nope... I'll take a look at this in next few days and get back to you. What if you remove the first listener - does it still only fire one?

**Comment by jamesmh** [comment]
Perhaps you didn't register all the listeners with the DI container?

**Comment by akytsun** [comment]
at Configure Services I've added next:
```
services.AddQueue();
services.AddEvents();
services.AddTransient<MyListener>();
```
at Configure:
```
 var provider = app.ApplicationServices;
            provider.ConfigureQueue().LogQueuedTaskProgress(provider.GetService<ILogger<IQueue>>()).OnError(ex =>
            {
                provider.GetService<ILogger<IQueue>>().LogError(ex, "Smth wrong in Coravel");
            });

            IEventRegistration registration = provider.ConfigureEvents();

            registration
            .Register<MyEvent>()
            .Subscribe<MyListener>();

```

I have only one Listener registered(

**Comment by akytsun** [comment]
Also, I can reproduce a similar behavior but use `QueueInvocable `. Not all registered calls were invoked

**Comment by jamesmh** [comment]
Yes, after the consummation delay the entire queue should clear. I'll see if I can get a sample running to verify (this should be working though...)

**Comment by jamesmh** [comment]
I created a simple sample to test these things:

https://github.com/jamesmh/coravel-multi-queue-sample

**Comment by jamesmh** [comment]
If that still doesn't help I think you'll have to post your listener code

**Comment by akytsun** [comment]
James, I'm not using scheduler for publish events. I'm using
queue.BroadcastEvent in my apicontroller action method. Maybe problem with
queue instance which injected through DI into controller?

Пн, 20 січ. 2020, 17:59 користувач James Hickey <notifications@github.com>
пише:

**Comment by jamesmh** [comment]
Yes, I know. The scheduler is just to simulate someone queuing via the system. That same code could be moved to a controller and should work. 

You can comment out the scheduler code in `Startup.cs` and paste this into the sample controller:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using coravelMultiQueueSample.Models;
using coravelMultiQueueSample.Events;
using coravelMultiQueueSample.Invocables;
using Coravel.Queuing.Interfaces;

namespace coravelMultiQueueSample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IQueue _queue;

        public HomeController(ILogger<HomeController> logger, IQueue queue)
        {
            _logger = logger;
            _queue = queue;
        }

        public IActionResult Index()
        {
            _queue.QueueBroadcast(new TestEvent());
            _queue.QueueInvocable<InvocableOne>();
            _queue.QueueInvocable<InvocableTwo>();
            _queue.QueueInvocable<InvocableThree>();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

```

**Comment by jamesmh** [comment]
Did you still need help with this?
