### ISSUE TITLE
IInvocable recurring tasks that can be cancelled

### ISSUE THREAD

**Issue by schmitch** [jamesmh/coravel#133]
**Describe the solution you'd like**
it would be cool if a `ICancellableTask` would also exists for the scheduler.
we actually have an application that runs for many hours, but sometimes it gets restarted (updated) unfortunatly our tasks are quite long > 3 hours and they should be cancelled, so it would be good to inject a `CancellationToken` that basically gets triggered when a shutdown is triggered.

**Comment by Blinke** [comment]
Sounds like a reasonable use case to me. If @jamesmh agrees I could look into implementing this.

**Comment by jamesmh** [comment]
Sure thing @Blinke 👍

For reference, check out these tests for the "queue with cancellation token" feature. That might help?
https://github.com/jamesmh/coravel/blob/master/Src/UnitTests/CoravelUnitTests/Queuing/CancellableInvocableForQueueTests.cs

We'll need to pass in the cancellation token that's supplied at the highest level (supplied by the framework) [see here](https://github.com/jamesmh/coravel/blob/master/Src/Coravel/Scheduling/HostedService/SchedulerHost.cs#L28). That will be passed into the scheduler before "running" it with the timer. 

That token should be cancelled by the framework when the application is closing. We won't have to do anything with the token ourselves (other than supply it to the developer).

Try creating a new interface with a property (holding the token reference).In the scheduler code we'll check for the interface being implemented on the type being scheduled and assign the token to that instance if it indeed implements that interface.

This way we won't need to change any of the existing schedule methods, etc. All the developer needs to do is implement a new interface and he/she is good to go (even with existing invocables).

Further than that, let me know if you need any help 🤷‍♂️

**Comment by jamesmh** [comment]
Done by @Blinke 

See docs: https://docs.coravel.net/Scheduler/#invocables

Available in 3.3.0
