### ISSUE TITLE
Feat: Configure event listeners in ConfigureServices with automatic service registration.

### ISSUE THREAD

**Issue by ryanelian** [jamesmh/coravel#142]
![image](https://user-images.githubusercontent.com/8892187/75443739-a070cb80-5994-11ea-893f-d0a924682ab0.png)

**Describe the solution you'd like**

Currently event listeners can only be configured after the service provider has been built AND requires the listener classes to be added manually to the DI.

This is not ideal for maintainability because the code for configuring the events are split in two places.

There should be a better API for handling this:

```cs
IEventRegistration hub = services.AddEvents();
hub.Register<ForgotPasswordEvent>()
    .Subscribe<ForgotPasswordEventListener>(); // Automatically registers ForgotPasswordEventListener in DI
hub.Register<CreateAccountEvent>()
    .Subscribe<CreateAccountEventListener>(); // Automatically registers CreateAccountEventListener in DI
```

**Describe alternatives you've considered**

- Refactoring into two extension methods, but this also still limits registration in two different places.

**Comment by jamesmh** [comment]
Thanks for your feedback!

Your comment:
>This is not ideal for maintainability because the code for configuring the events are split in two places.

This would apply to most .NET Core configuration APIs. Take for example configuring [razor pages](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio#razor-pages). The same applies for MVC and many .NET Core features.

One reason is that before the service provider is built the services + all their dependencies can't be retrieved since the provider doesn't exist. 

So this technically won't work.

That being said, there are ways to auto register all event listener classes which could make things easier (but that would be a new feature request 😉)

**Comment by ryanelian** [comment]
> So this technically won't work.

The object may not exist at the time of registration, but can't they be stored in an array or something before it is being invoked during `Configure`?

e.g. The method in `ConfigureEvents` 

```cs
public void ConfigureEvents(IServiceProvider serviceProvider)
{
INotActuallyRealEventRegistration hub = services.AddEvents();
hub.Register<ForgotPasswordEvent>()
    .Subscribe<ForgotPasswordEventListener>(); // Automatically registers ForgotPasswordEventListener in DI
hub.Register<CreateAccountEvent>()
    .Subscribe<CreateAccountEventListener>(); // Automatically registers CreateAccountEventListener in DI
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
app.ApplicationServices.ConfigureEvents(); // gets the configured INotActuallyRealEventRegistration to configure the real IEventRegistration 
}
```

> That being said, there are ways to auto register all event listener classes which could make things easier (but that would be a new feature request 😉)

Hell yeah that would be dope, just like FluentValidation.

![image](https://user-images.githubusercontent.com/8892187/75450857-247d8000-59a2-11ea-8add-773628a22a10.png)

https://github.com/ryanelian/FluentValidation.Blazor#fluentvalidationdependencyinjectionextensions

**Comment by jamesmh** [comment]
Looks like your idea would work. I'm not so convinced the benefits are worth it though?

I would agree though that being able to auto register all events + listeners would just be a great alternative overall. 👍

**Comment by ryanelian** [comment]
>  I'm not so convinced the benefits are worth it though?

I believe my suggested pattern conforms to common .NET library configurations pattern, for example:

- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1

- https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.1&tabs=visual-studio#add-and-configure-swagger-middleware

- http://docs.identityserver.io/en/latest/topics/startup.html

The most extensive configurations are done in the `Configure` services part of the code and they auto-registers services required to run the library.

Then when it comes to actually "running" the services in the `Configure` part, that part is just a one-liner with no option.

```cs
        public void ConfigureServices(IServiceCollection services)
        {
             services.AddIdentityServer(...)
                         .AddProfileService<MyProfileService> // auto-registers MyProfileService to DI
                         .AddResourceStore<MyResourceStore> // auto-registers MyResourceStore to DI
                         .AddClientStore<MyClientStore> // auto-registers MyClientStore to DI
                         .AddCorsPolicyService<MyCorsPolicyService> // auto-registers MyCorsPolicyService to DI
                         .AddOperationalStore<MyOperationalStore> // auto-registers MyOperationalStore to DI

            services.AddAuthentication("MyApp").AddCookie("MyApp", options =>
            {
            });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
             app.UseAuthentication();
             app.UseAuthorization();
             app.UseIdentityServer();
        }
```

----

So if anything, the worthiness of this feature is that it allows Coravel to automatically register required services AND to conform to common configuration pattern:

```cs
        public void ConfigureServices(IServiceCollection services)
        {
             var hub = services.AddEvents();
             hub.Register<MyEvent>.Subscribe<MyEventListener>();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
             app.UseCoravelEvents();
        }
```

**Comment by jamesmh** [comment]
I think the autoregister feature, like you said, would address all the concerns you have. And that's pretty typical - if you have a listener then you probably want to use it (otherwise, there's still the ability to register by hand).

I'll close this use #148 moving forward 👍
