### ISSUE TITLE
Queue IInvocables with Params

### ISSUE THREAD

**Issue by schmitch** [jamesmh/coravel#145]
**Describe the solution you'd like**
Same as #128, just for a Queue.
PR: #146

**Comment by ryanelian** [comment]
I believe passing parameter to queued Coravel jobs can be done using Queue + Event Broadcast

https://docs.coravel.net/Queuing/#queuing-an-event-broadcast

https://docs.coravel.net/Events/

**Comment by schmitch** [comment]
well, first of the events are quite complex. and it also won't work if I need to have multiple running jobs at the same time (which I need). basically I need to schedule **many** things at the same time. thus a events are `m:1` while I need `m:n`. Which will only work, when passing params to the queue directly.

**Comment by jamesmh** [comment]
@ryanelian is correct. There's a past thread on this: https://github.com/jamesmh/coravel/issues/62#issuecomment-433429268

If you read through, there's various ways to introduce params already. Also this was the catalyst for the `QueueBroadcast` feature.

Although a dedicated method for queuing with params still may be a handy convenience.

**Comment by schmitch** [comment]
well in my case a Listener would not be enough. Since a listener will only do one thing at a time, while a queue does many things at a time. I have DI parameters **and** normal parameters. So to support it I would need something like that:

```
constructor(IServiceScopeFactory _factory) {
}
...
public void QueueTask(int id)
{
 this._queue.QueueAsyncTask(async() => {
    using scope = _factory.CreateScope();
    var invocable = scope.ServiceProvider.GetRequiredService<MyInvocable>();
    invocable.Param = id;
    await invocable.Invoke();
 });
}
```

while it's totally possible to write such code, it's probablly better to just queue it with params, it's also way less error prone.

**Comment by jamesmh** [comment]
#156 fixes this. I ended up using a particular approach that will support future features I have in mind 😊

See https://docs.coravel.net/Queuing/#queue-an-invocable-with-a-payload
