### ISSUE TITLE
Support of delayed jobs?

### ISSUE THREAD

**Issue by hmqgg** [jamesmh/coravel#149]
**Describe the solution you'd like**
```C#
interface IDelayedJob
{
    void Queue(Action action, Timespan delay);
    //...
}
```
Wait `delay`, then invoke `action`.

**Describe alternatives you've considered**
Use `IQueue` with `CancellationToken`.
In the action, wait for the token cancellation, then process the workload.

**Comment by Blinke** [comment]
#96 discussed supporting running one 
-off jobs on the scheduler, potentially also allowing you to specifiy when to schedule it for. Maybe that would be a better solution for this as well?

**Comment by jamesmh** [comment]
Ya tough. Scheduling "once" and queuing for a specific delay are very similar. Basically the exact same thing if in both cases we are specifying a delay time.

**Comment by Blinke** [comment]
Right. In my opinion it would make more sense for the scheduler to handle it. Running invocables at specific times is already its main purpose.

**Comment by jamesmh** [comment]
I would agree.

@hmqgg I'm going to close this but the reason being that #96 covers the use case.

For example, the API that comes to mind is something like:

`scheduler
    .EveryHour()
    .Once()`;

Or, potentially:

`scheduler
    .In(DateTime.FromMinutes(5))` as shorthand-ish way of doing it.
