### ISSUE TITLE
Cannot queue new tasks while queue is consuming

### ISSUE THREAD

**Issue by dawid1103** [jamesmh/coravel#152]
**Describe the bug**
When the queue is performing tasks and adds new tasks to the queue, the queue does not take up new tasks after processing. When I was debugging, the queue was empty. Tasks are gone.

**Affected Coravel Feature**
Queuing

**Expected behaviour**
I would expect jobs to be postponed and the queue to start processing them as soon as the previous processing has finished.

**Comment by jamesmh** [comment]
I'll have a look - thanks!

**Comment by dawid1103** [comment]
@jamesmh check for long running tasks. Like a export or sth, 5-10 min

**Comment by jamesmh** [comment]
Can confirm queue has some issues. Will keep digging and let you know.

**Comment by jamesmh** [comment]
Looks like 3.0.0 is fine. 3.1.0 is not (and moving forward)

So I'll have to take a look at 3.1.0 specifically and see what changed. For now, if you can, use 3.0.0 :(

**Comment by dawid1103** [comment]
Version 3.0.0 is fine. I confirm ;) I'll try to help you. I will try to find out the issue also.

**Comment by jamesmh** [comment]
I made some big changes to the queue in 3.1.0. So far I've caught the bug with a new unit test 👍

I'm thinking of doing some refactoring on that code too. It's getting messy enough that it's now causing bugs...so it's time to clean it up lol. I'm thinking of getting it done hopefully by the weekend, since this is pretty critical.

**Comment by jamesmh** [comment]
If you do find anything please let me know 👍

**Comment by dawid1103** [comment]
here Coravel\Queuing\Queue.cs : 86 

Use this 
`Task.WaitAll(dequeuedTasks.Select(InvokeTask).ToArray());`

instead of
`await Task.WhenAll(dequeuedTasks.Select(t => InvokeTask(t)));`

**Comment by jamesmh** [comment]
Frig. Because of lazy execution eh? I'll give that a try. 👏

**Comment by dawid1103** [comment]
Or you know what. Check this. Try to return task from Task.WhenAll -> `Task result = Task.WhenAll(dequeuedTasks.Select(InvokeTask).ToArray());` but u have to change the method return type also `public async Task<Task> ConsumeQueueAsync()`. In both cases the test pass.

Here some explanations

`Task.WaitAll` blocks the current thread until everything has completed.
`Task.WhenAll` returns a task which represents the action of waiting until everything has completed.
That means that from an async method, you can use:
`await Task.WhenAll(tasks);`
https://stackoverflow.com/a/6123432

**Comment by jamesmh** [comment]
I'm still getting the issue, but good find none-the-less.

**Comment by jamesmh** [comment]
k Found the issue. You were really close! I'll be pushing asap 👍

**Comment by dawid1103** [comment]
Okay, that's the IEnumerable .. Dynamic enumeration in WhenAll. Pff :D good one

**Comment by jamesmh** [comment]
It's all pushed to nuget under 3.3.1 now. Thanks for the help! Not sure I would have picked that one up so quickly otherwise 😅

And now we've got a test covering it so 👍
