### ISSUE TITLE
Wrong LogLevel for invocation start and finish

### ISSUE THREAD

**Issue by Ezergil** [jamesmh/coravel#160]
I think it would be better to change those messages level to Trace or Debug, because thse messages are absolutely useless
                    this._logger?.LogInformation("Scheduled task started...");
It also could be usefull to put information about which IINvocable was called, like  Scheduled task for ConcreteInvocableName started
Thanks!

UPD: error messages are useless too
http://joxi.ru/gmvbo10uqE3Exm
U should Log excepton, not exception message. There are no stacktrace and other info that is crucial for logging

**Comment by Ezergil** [comment]
@jamesmh https://github.com/jamesmh/coravel/pull/161 i added PR for changes described there, check it please
Thanks in advance

**Comment by Ezergil** [comment]
@jamesmh would apreciate nuget update :)
also could help you with some feature implementation if you'll need any :)

**Comment by jamesmh** [comment]
Will do, I've got another change I'm going to try and shove in sometime this week too :+1:

**Comment by Ezergil** [comment]
> Will do, I've got another change I'm going to try and shove in sometime this week too :+1:

Thanks :)
