### ISSUE TITLE
IsRunning False

### ISSUE THREAD

**Issue by jeffrosenthal** [jamesmh/coravel#162]
I am new to Coravel and trying to call a method every minute.  In my configservices I have services.AddScheduler();

and then in my mainviewmodel I get a reference to the IScheduler and call
            _scheduler.ScheduleAsync(async () => { await UpdateTimeSinceBoot(); })
                .EveryMinute();

My method never gets called and when I look at _scheduler is indicates IsRunning false.

This additional info might be requested:
This is using  .Net Core 3.1
It is a WPF app (no IIS)
The host is in proc

Do I need to enable this some place?

**Comment by jamesmh** [comment]
Try putting the code to schedule the actual task inside the startup `Configure` method....not sure if that exists with WPF?

See https://docs.coravel.net/Scheduler/#config

Otherwise, let me know. 👍

**Comment by jeffrosenthal** [comment]
OK - First I just tried this in the VM
            ```
_serviceProvider.UseScheduler(scheduler =>
            {
                scheduler.Schedule(
                        UpdateTimeSinceBoot)
                    .EveryMinute();
            });

```

That did not work.
To put it in the app.xaml.cs will take a few more minutes

**Comment by jeffrosenthal** [comment]
That is not working either (the best I could do)
In my OnStartup after I config all the services I get a reference and schedule
`            serviceProvider.UseScheduler(scheduler =>
                {
                    scheduler.Schedule(
                            vm.UpdateTimeSinceBoot)
                        .EveryFiveSeconds();
                });
`

It never gets called

**Comment by jeffrosenthal** [comment]
What is it that has to be called to get it running?

**Comment by jeffrosenthal** [comment]
Well I got it working

`            var mainVM = CtiServiceProvider.GetRequiredService<MainViewModel>();
            host.Services.UseScheduler(scheduler =>
                scheduler
                    .Schedule(() => mainVM.UpdateTimeSinceBoot())
                    .EveryMinute()
            );

           

            host.RunAsync();
`

host.RunAsync() was what it needed.  My app does not need it but Coravel does.

**Comment by jamesmh** [comment]
Great, glad you were able to solve the issue 👍
