### ISSUE TITLE
CancellationToken for WorkerService

### ISSUE THREAD

**Issue by smigalni** [jamesmh/coravel#163]
Hi

I am creating a worker service which will be running as windows service on prem. I need to cancel all my operations when windows service is stopped by implementing cancellation token in my application.
I would propose something like this
```
 public class MyFirstInvocable : IInvocableWithCancellationToken
    {
        public Task Invoke(CancellationToken cancellation)
        {
            Console.WriteLine("This is my first invocable!");
            return Task.CompletedTask;
        }
    }
```
and when I stop my application cancellation token is cancelled.

best regards Sergey
In any case, thanks for your work. This is a really useful project.

**Comment by jamesmh** [comment]
This exists:

For scheduling: https://docs.coravel.net/Scheduler/#invocables

For Queuing: https://docs.coravel.net/Queuing/#queuing-cancellable-invocables

FYI These are separate interfaces right now but I'm thinking of changing them to share the one interface at some point.
