### ISSUE TITLE
Scheduler integration tests

### ISSUE THREAD

**Issue by arekor** [jamesmh/coravel#165]
Hello

How can I run task scheduler in integration tests?

I have.

        private readonly ITestOutputHelper _testOutputHelper;

        public Tests(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }

        [Fact]
        public async Task Test()
        {
            var services = new ServiceCollection();

            services.AddScheduler();
            var serviceProvider = services.BuildServiceProvider();
            serviceProvider.UseScheduler(scheduler =>
            {
                scheduler.Schedule(() => { _testOutputHelper.WriteLine("Test"); })
                    .EverySecond();
            });

            await Task.Delay(3000);
        }

It doesn't start.

Thanks for help.

**Comment by arekor** [comment]
I found out that I have to start hosted service.
`_hostService = serviceProvider.GetService<IHostedService>();
            await _hostService.StartAsync(CancellationToken.None);`
Thanks.

**Comment by jamesmh** [comment]
Cool 👍
