### ISSUE TITLE
More examples for console applications

### ISSUE THREAD

**Issue by bchris999** [jamesmh/coravel#166]
Can you provide some more detailed examples for console applications please? It may be my lack of .NET knowledge, but how to do you use this from the docs in a console app?

Logging Executed Task Progress
Coravel uses the ILogger .NET Core interface to allow logging task progress:

var provider = app.ApplicationServices;
provider
    .ConfigureQueue()
    .LogQueuedTaskProgress(provider.GetService<ILogger<IQueue>>());

**Comment by jamesmh** [comment]
Check out this sample in the repo: https://github.com/jamesmh/coravel/blob/master/Samples/HostBuilderConsole/Program.cs

It might be a bit different since that sample is from an older .NET Core version, but it should point you in the right direction.

Let me know if that helps or not 👍

**Comment by bchris999** [comment]
Thanks James. I used that example to get me started, but a non-web host doesn't seem to include the ApplicationServices bit in any example I can find (i.e. there is no Startup for console apps) so I'm at a loss as how to enable The LogQueueTaskProgress. I'm using CreateDefaultBuilder so logging is configured.

**Comment by jamesmh** [comment]
Try this as a starting point:

```c#
using Microsoft.Extensions.DependencyInjection;
using Coravel.Queuing.Interfaces;
using Coravel;
using System.IO;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace HostBuilderWithQueue
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.SetBasePath(Directory.GetCurrentDirectory());
                    configApp.AddEnvironmentVariables(prefix: "PREFIX_");
                    configApp.AddCommandLine(args);
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddQueue();
                })
                .Build();

            var logger = host.Services.GetService<ILogger<IQueue>>();
            host.Services
                .ConfigureQueue()
                .LogQueuedTaskProgress(logger);

            // Run it!
            host.Run();
        }
    }
}

```

**Comment by jamesmh** [comment]
How have things progressed on this? Did the sample help?

**Comment by jamesmh** [comment]
Let me know if you need anymore help. Closing for now.
