### ISSUE TITLE
cron expression malformed

### ISSUE THREAD

**Issue by Myhindash** [jamesmh/coravel#170]
Hi,

I'm using the caravel as a schedule worker, sometime i need to make run for a process for one time.
my request is as below:

I need to create a new schedule to be executed one time using the crone expression like
"0 35 05 30 5 ? 2020" which means "At 05:35:00am, on the 30th day, in May, in 2020"

how can I do that with the Coravel, cause I received that error in the subject
also I have checked the code that the cron expression expecting 5 digits only
or if there is any work around to resolve this

thanks

**Comment by jamesmh** [comment]
No, the cron expression right now represents:

Min, hours, day of month, month, day of week.

I believe there is another issue for the ability to schedule a one time job...

**Comment by 3than7** [comment]
this may help you to create what you need

https://crontab.guru/examples.html

just keep in mind to use standard expression without "?"

**Comment by jamesmh** [comment]
Check out issue https://github.com/jamesmh/coravel/issues/96
