### ISSUE TITLE
 Coravel Caching key expiry questions

### ISSUE THREAD

**Issue by KawtharEbrahim97** [jamesmh/coravel#177]
I need to understand more how caching expiry work. 
- When the key is getting expired? is it after the timespan specified while calling the Remember method? 
- Do calling the Remember method will fill the cache again if the key expired?
- In my case I am calling the Remember method and after that I am calling the GetAsync method ? in this case do we need to check the HasAsync method? what if the HasAsync method is false .. what is the action we need to take .. calling the Remember method  again ?

**Comment by KawtharEbrahim97** [comment]
Is doing it this way is the best practice ?

`bool hasKey = false;
            if (hasKey)
            {
                Transactions = await _cache.GetAsync<List<Transaction>>("TransactionCacheKey");
            }
            else
            {
                hasEthixEFTSKey = await _cache.HasAsync("TransactionCacheKey");
            }`

**Comment by jamesmh** [comment]
1. The key expires when the time frame is up (even if you don't call `Remember`, etc.).
2. Yes
3. Your code should look like this:

```csharp
Transactions = _cache.Remember<List<Transaction>>("TransactionsCacheKey", FetchTransactions, TimeSpan.FromMinutes(5));
```

**Comment by KawtharEbrahim97** [comment]
> 1. The key expires when the time frame is up (even if you don't call `Remember`, etc.).
> 2. Yes
> 3. Your code should look like this:
> 
> ```cs
> Transactions = _cache.Remember<List<Transaction>>("TransactionsCacheKey", FetchTransactions, TimeSpan.FromMinutes(5));
> ```

This is what I looking for. Thank you very much.

**Comment by jamesmh** [comment]
Great!
