### ISSUE TITLE
Consider splitting Coravel into smaller packages

### ISSUE THREAD

**Issue by Dreamescaper** [jamesmh/coravel#186]
First of all, thanks a lot for the great library!

I only use Task Scheduler from Coravel (at least for now), and personally I'd prefer to be able not to reference other functionality until I need that. 

I think it would be great if Coraval packages would be split something like that:
- `Coravel` - meta-package with dependencies for all packages below - to preserve backward compatibility,
- `Coravel.Core` - common classes, e.g. Invocables,
- `Coravel.Cache` - depends on `Coravel.Core` (if needed),
- `Coravel.Events` - depends on `Coravel.Core` (if needed),
- `Coravel.Queuing` - depends on `Coravel.Core` (and maybe on `Coravel.Events`?),
- `Coravel.Scheduling` - depends on `Coravel.Core` (and maybe on `Coravel.Events`?).

Thanks!

**Comment by jamesmh** [comment]
Yes, this is something that has come up before.

I'll keep this open but will most likely look at doing this as part of a major revision/piece of work 🙂

**Comment by neil-timmerman** [comment]
I like this idea too.

**Comment by jamesmh** [comment]
Going to close. I don't see this happening ATM.
