### ISSUE TITLE
Schedulers skips one of the schedule after running smoothly for couple of days

### ISSUE THREAD

**Issue by KunalPandhare** [jamesmh/coravel#187]
**Describe the bug**
I have implemented the Worker service (Installed as Windows-service) with 3 invocable jobs. The jobs are scheduled using CRON expression to run Daily at 9:00 am ("0 09 * * 1-5), 10:00 AM ("0 10 * * 1-5) and  5:00 PM ("0 17 * * 1-5) respectively. 

The cron shedules assigned once per life time of windows service when windows service is started. I have observed that after for 10-12 days it worked smoothly and fired all three Jobs at scheduled time. However on certain Wednesday the Job did not run. I found that the windows-service was still running and Event-viewer on windows did not show any error happened internally since last job invocation.

This happened in Production environment and I was clueless what could have one wrong ? What could be the issue here?

.NetCore 3.1 with Coravel Scheduling 3.6.1

**Comment by jamesmh** [comment]
Not sure 🤷‍♂️

There are two things you can try to implement to figure this out in production:

https://docs.coravel.net/Scheduler/#global-error-handling

https://docs.coravel.net/Scheduler/#logging-executed-task-progress

**Comment by KunalPandhare** [comment]
Thanks @jamesmh for quick response. I will implement the global error handling from next time onward it will help me.

I know that the schedules are stored in-Memory during the life time of application. Now in case windows service the life time will be too long from weekly to months etc. 
Is it possible that the Schedulers/Schedules stored in memory got wiped out due to some kind of memory cleanup or so ? Or may be CRON expressions or something of that sort was wiped out from memory ?

**Comment by jamesmh** [comment]
no, but it is possible that you deployed the application at the exact time the schedules were due also? For the few seconds that your application might have been "down" possibly?

**Comment by KunalPandhare** [comment]
that's not the case, The application was running for weeks and suddenly scheduler did not run on one day.

**Comment by KunalPandhare** [comment]
Happened again. 

This time we already have Try Catch around scheduler initialization, OnError and TaskProgressLogger is also set.

Along with 5 PM schedule I have 4.45 PM and 5.05 PM Schedules. (Pre and post operations)
Now it looks like 4.45PM and 5.05 PM  was triggered but 5PM scheduler did not trigger. 

Its is strange as well as Frustrating. Since we are using this is Production environment its not acceptable. 

Seriously thinking of moving away from Coravel unless makers have some answer to it.

**Comment by jamesmh** [comment]
At this point I'd need to see your code, how you've configured your windows service, how you deploy it, etc.

Otherwise, it's just shooting in the dark 🤷‍♂️

**Comment by KunalPandhare** [comment]
I will provide the sample worker service that i have created in over the weekend

**Comment by jamesmh** [comment]
I know others (including myself) who've had coravel running for weeks with no issues yet. This is still the first I've had come through, so it might be something specific about how you've configured something, an issue with the service specifically, or could be a legit issue with something like the schedule workers potentially.

Great - once you're able to provide the sample if you could also share a screenshot of how the windows service is configured?

Thanks! 😊

**Comment by HaydnDias** [comment]
@jamesmh I've had similar issues, took us a while to track down but we realised the preventoverlap feature locked out a task for 24 hours? It'd be nice if that was documented somewhere, and even nicer if it was configurable. We had a task that runs every 15 minutes overrun by a few minutes and then didn't run at all till the next day.

**Comment by jamesmh** [comment]
Hmmm, if a task doesn't release its lock then that's a problem. When the task finishes or throws an exception the lock should be released. That "24 hours" feature is supposed to be a timeout - so if a task takes longer than 24 hours to run then the lock will release. But yes, would be nice to make that configurable. But again, under the circumstances, you mentioned there's something else at play.

Any idea under what circumstances that seems to occur?

**Comment by alhardy** [comment]
@jamesmh I have this issue also using pro.

We have two relatively simple 'IInvocable' jobs with a try catch wrapping and log an throw any exceptions.

On occasion the jobs do not run, nothing logged about starting up or any fails failures. We have monitoring on the output of these jobs, when alerted we jump it and run the job manually and everything works fine.

The prevent overlap feature is enabled.

No deployments where made anywhere near the schedule execution time

Any other ideas?

**Comment by jamesmh** [comment]
Update: So I took a Demo project, put it into a docker container, and gave it an abysmal CPU limit (e.g. `--cpus=".05"`). I'm running this with the fixed code (not deployed yet) so it detects when a tick is missed and logs an informational message. I suspect this is the scenario most are experiencing and, again, depends on how often your schedules run, how critical they are, etc.

The fix seems to be working and I was able to replicate the issue 👍. This is a big change to how Coravel works, so I think this will become a major version package update.

![image](https://github.com/jamesmh/coravel/assets/7213174/af0e4bbc-c6a8-43eb-a988-e1920ce79713)

**Comment by alhardy** [comment]
Thanks for the details @jamesmh.

We are running on an Azure App Service with 1 CPU. We're experiencing the issue sometimes from a few times per week, to once a fortnight.

We have alerts fired when the output of the job is missing, when we check the logs there is no job execution. We're running manually for now when we get this alerts. They are morning jobs though so it's a little painful for those oncall.

Looking forward to giving the fix a go! Thanks!

**Comment by jamesmh** [comment]
This fix is available in the pre-release package version `5.0.3-prerelease`

**Comment by jamesmh** [comment]
`5.0.3` should be available now, and addresses this issue. Will leave this issue open as a place to comment in the event issues are discovered. Will close once some time has passed 👍

**Comment by jamesmh** [comment]
Closing - if there are any issues please reopen or create a new issue. Thank you! 🙂
