### ISSUE TITLE
Number of running queue tasks not decremented when task fails

### ISSUE THREAD

**Issue by temesinko** [jamesmh/coravel#191]
**Describe the bug**
When a task fails, the number of running tasks in a queue is not decremented.

**Affected Coravel Feature**
Queuing

**Expected behaviour**
I expect the number of running tasks in a queue to be decremented even if a task fails. I think [this line](https://github.com/jamesmh/coravel/blob/612204c49ed4f8e7e4523620a41c948937cb7992/Src/Coravel/Queuing/Queue.cs#L211) should be moved to a `finally` block.

What do you think, @jamesmh?

**Comment by jamesmh** [comment]
Yup, good catch 😊

Did you want to do the fix?

**Comment by jamesmh** [comment]
Thanks for the awesome fix 😎

**Comment by temesinko** [comment]
You're welcome! Thank you very much for this wonderful piece of software. It's perfect for our needs! :)
