### ISSUE TITLE
Oracle.EntityFramework

### ISSUE THREAD

**Issue by massimomannoni** [jamesmh/coravel#201]
Hi James,
      I'm migrating my local solution written using Sql Server to an Env operating on Oracle db.
Running Add-Migration I got an error related to IdentityUserLogin.
Have you any suggestion to me ?
thanks in advance
Massimo M.

**Comment by jamesmh** [comment]
If you're using Coravel, Coravel doesn't affect EF.

If you're using Coravel.Pro, then it might be something related to this -> https://www.docs.pro.coravel.net/Installation/#potential-issue-with-sql-server
