### ISSUE TITLE
Run scheduler based on timetable stored in Database 

### ISSUE THREAD

**Issue by only1sham** [jamesmh/coravel#202]
Hi,

Is it possible to run this scheduler based on some a schedule that is stored in SQL tables - like every Monday at 1 pm, etc.? If yes, can you please provide some pointers or sample code if possible?

**Comment by jamesmh** [comment]
I don't have a sample, but you could build that yourself. Store the schedules (perhaps as cron expressions?). Then when your app starts, fetch those values and configure Coravel using them?

**Comment by mihaimyh** [comment]
> I don't have a sample, but you could build that yourself. Store the schedules (perhaps as cron expressions?). Then when your app starts, fetch those values and configure Coravel using them?

This approach will not get new values entered in db after the app starts. I am testing a new approach to configure a new scheduler at a new at the end of the `Invoke()` method.

**Comment by tashe** [comment]
I'm also looking into this approach.

Does this mean that my application needs to be restarted every time there are changes made to the schedules in the database?

We are interested in dynamically adding new schedules for Jobs while the application is running.

Is that possible with the database approach or is there a feature in the Pro version that allows that?

These Jobs would require parameters, as each job can be scheduled for a different customer.

**Comment by jamesmh** [comment]
You could do this, but again would need to code the database portion yourself. There's [another issue](https://github.com/jamesmh/coravel/issues/216) with details about how you might add/remove schedules dynamically.

With Coravel Pro, you can add schedules at run-time from the UI but not dynamically - as that would need to be coded.

And yes, you can [schedule tasks using parameters ](https://docs.coravel.net/Scheduler/#scheduling-with-additional-parameters). Hopefully that helps :)
