### ISSUE TITLE
referencing microsoft.aspnetcore.mvc.razorpages.pagemodel

### ISSUE THREAD

**Issue by jopia** [jamesmh/coravel#204]
hi,
Is it possible to inherit both IInvocable and razor page model?
I want to embed a callbackurl in the email e.g. 
   var callbackUrl = Url.Page(
             "/Account/ConfirmTask",
             pageHandler: null,
             values: new { area = "Identity", code = code, mTaskEventsId = '8' },
             protocol: Request.Scheme);

There are problems with Url.Page and Request.Scheme....
Similar problems exist with hangfire where i can't send slightly complex emails

**Comment by jamesmh** [comment]
I have no idea lol. Sounds like a class that might be doing too much? (SRP)

Perhaps using a payload and queuing the email would work? -> https://docs.coravel.net/Queuing/#queue-with-a-payload
