### ISSUE TITLE
Seems like scheduler Daily() does not work

### ISSUE THREAD

**Issue by risogolo** [jamesmh/coravel#206]
**Describe the bug**
Using version 4.0.2
Im trying to set scheduler to run Daily

**Affected Coravel Feature**
Seems like the scheduler.Daily() does not trigger anything, when I use for example EveryMinute() then thecode I need is executed

**Expected behaviour**
Scheduler will execute the code at midnight

**Comment by jamesmh** [comment]
`.Daily()` will run at midnight UTC. Are you making sure you're trying to run at 12:00am UTC?

**Comment by risogolo** [comment]
yes, It ran 24h, Im logging whether the method is executed, and it is not, the type of the scheduler used is the only diferrence.

**Comment by jamesmh** [comment]
Ok great. Do you have a code sample that reproduces the issue?

**Comment by risogolo** [comment]
```
host.Services.UseScheduler(scheduler =>
{
   scheduler.Schedule<OrderStateCancellation>().Daily();
}
});
host.Run();
```



`services.AddTransient<OrderStateCancellation>();`

```
 public class OrderStateCancellation : IInvocable
    {
        private readonly IOrderPublisherService _orderPublisherService;

        public OrderStateCancellation(IOrderPublisherService orderPublisherService)
        {
            _orderPublisherService = orderPublisherService;
        }

        public async Task Invoke()
        {
            await _orderPublisherService.CancelAllOrdersAsync();
        }
    }
```

**Comment by risogolo** [comment]
My fault..., it works
