### ISSUE TITLE
Scheduled task DailyAtHour sometimes skip weekend

### ISSUE THREAD

**Issue by Kasta11111** [jamesmh/coravel#211]
**Describe the bug**
`Schedule().DailyAtHour()` sometimes skip weekend.

After few weeks of using scheduling, I started logging DailyAtHour task because I noticed that the task didn't run every day. After almost a month of logging, I noticed that two weekends were skipped. Started logging at 2021-01-04 to 2021-02-01. Weekends 2021-01-16/2021-01-17 and 2021-01-30/2021-01-31 was skipped.

**Affected Coravel Feature**
Scheduling

**Expected behaviour**
`DailyAtHour()` to run every day at a given hour.

**Version**
Coravel 4.0.1
AspNetCore 3.1.8

**Comment by jamesmh** [comment]
Thanks for this 🙂 Just to give me more insight into your application, etc. are weekends generally more or less under load? Were there any deployments or was there only one deployment before logging the application for the month?

**Comment by Kasta11111** [comment]
The project is still under development, so "production" (production environment on the server for testing purposes) has only a few users (like 3 concurrent connections) mostly during the working days. There were a few deployments during logging duration, but always on working days and no deployment straight after weekends when scheduling did not work. That means that scheduling started working again by itself without any intervention from me.

Do you need some more info?

**Comment by Kasta11111** [comment]
So I noticed that is not only `DailyAtHour()`, but also `Hourly()` and `EveryFiveMinutes()` which were the only three intervals I tried. `DailyAtHour()` and `Hourly()` did not start at all during this week. And `EveryFiveMinutes()` started only a few times, you can see that on the attached image. The first time is log at the start of the function and the second is the end of the function.

![scheduler-every5min](https://user-images.githubusercontent.com/7083384/107198372-4c1ff980-69f5-11eb-8e9d-553a2c36f811.PNG)

Is possible that the server is in something like a "sleep mode" when there is no connection for some time? Because today 2021-02-08 I connected to the server before the first log (around 09:48:00) and then it started logging again.

![scheduler-every5min-after-connect](https://user-images.githubusercontent.com/7083384/107198914-044da200-69f6-11eb-8302-02001190c831.PNG)

**Comment by jamesmh** [comment]
If you are using IIS then that's possible (it's the default I believe) for the applications to "turn off" if they aren't getting traffic...

If you are using IIS then this makes sense. Check out a blog post like [this one](https://weblog.west-wind.com/posts/2013/oct/02/use-iis-application-initialization-for-keeping-aspnet-apps-alive) or google keeping IIS sites always on.

Let me know if that's the issue or not - thanks!

**Comment by Kasta11111** [comment]
Ok, that was the problem. The application turned off when has no traffic. Changing server options fixed this issue.

Thank you @jamesmh for your help. Also thank you for Coravel :) 👍

**Comment by jamesmh** [comment]
Awesome!
