### ISSUE TITLE
Question: When to use Invocable vs Action, or getting around named registrations in DI

### ISSUE THREAD

**Issue by bmildh** [jamesmh/coravel#213]
Hello!

I'm new to Coravel and MS DI. 

 I was thinking about using Coravel as a way to schedule a cli command to be run at different times. Let's call this command **opencli.exe**. Let's say I would like to have one instance of this running every ten minutes, and another instance of this running every fifteen minutes. The only difference would be the arguments. My first approach was to create a class called OpenCLI that implements IInvocable. It has path string field, and an argument string field. 

```c#
public class OpenCLI : IInvocable
{
        private readonly string _path;
        private readonly string _args;

        public OpenCLI(string path, string args)
        {
            _path = path;
            _args = args;
        }
        
        public Task Invoke()
        {
            // TODO: Invoke cli command with Microsoft.Diagnostics.Process
            return Task.CompletedTask;
        }
}
```

 But I realized that in MS DI, I cannot have named instances (registrations). 

 First attempt in code looked something like this, in Main.cs:
```c#
    IHost host = CreateHostBuilder(args).Build();
            host.Services.UseScheduler(scheduler =>
            {
                scheduler
                    .Schedule<OpenCLI>()
                    .EveryFiveSeconds();
             
                scheduler
                    .Schedule<OpenCLI>()
                    .EveryTenSeconds();

            });
            host.Run();
```
 And in the method CreateHostBuilder, were I register the providers, I got lost, like I could not figure out how i could make the code above be able to know which one of my instances is to be run every five seconds, and which one to be run every ten seconds. 

```c#
   public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args).ConfigureServices(services =>
                {
                    services.AddScheduler();
                    //services.AddTransient<IInvocable>(sp => new OpenCLI("/path/to/opencli.exe", "/C /A"));
                    
                });
```
 So, after a little reading about MS DI, I found out that it is not possible to have named instances. So I cannot schedule the correct invocable instance to the right interval. 

 So, when I was trying to find some other way of thinking about this, I realized that In scheduler, you can schedule an Action. Maybe that is a better way to resolve this? It feels, like, looking at the documentation and examples, when a class that is implementing IInvocable, then that class is a type of job that generally is not scheduled more than once in the schedule (like you would not schedule it everyhour AND everytenminutes). Do I understand that correctly?

 I was thinking that my application should read a json file at startup, this file should contain the path to the cli command and optional arguments to that cli, and with the scheduled time. My thinking was to like, read and parse this file, and create the appropriate IInvocable object, but since I cannot differentiate the instances, this approach feels wrong. 

 If anyone could share some insights into my shortcomings, different perspective to go about this, or shine some kind of light, any light, into this matter, It would be greatly appreciated.

**Comment by jamesmh** [comment]
Check out this part of the docs: https://docs.coravel.net/Scheduler/#scheduling-with-additional-parameters

Let me know that works for you 👍

**Comment by bmildh** [comment]
Dude! 

So happy right now. Thank you! Respect!

**Comment by jamesmh** [comment]
🥳
