### ISSUE TITLE
Task firing off twice during .EveryMinute()

### ISSUE THREAD

**Issue by smithb115** [jamesmh/coravel#214]
I seem to have come across an issue that I am having trouble figuring out is coming from the library itself or my configuration of the invocable I'm running. 

My project is a .NET Core Worker project that uses Coravel to schedule an invocable to run every minute. This invocable is a short-running Task (not an async method) that does a small database operation and returns a Task.CompletedTask on finishing, usually within a matter of a second or so. 

Inside my Program.cs in my host configuration I am adding the scheduler to the host builder:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddSingleton(Configuration);
                    services.AddTransient<JobRequestInvocable>();
                    services.AddScheduler();
                })
                .UseWindowsService()
                .UseSerilog();
```

And then before running the host, telling it to run the invocable every minute:
```
IHost host = CreateHostBuilder(args).Build();
host.Services.UseScheduler(scheduler =>
{
    scheduler.Schedule<JobRequestInvocable>().EveryMinute();
});
host.Run(); 
```

Now my basic invocable:

```
public Task Invoke()
{
    // short-running DB operation

    return Task.CompletedTask;
}
```

This seems to be running completely fine the majority of the time, but on occasion the invocable has run twice at the top of the minute. Below is one instance from my SEQ logs, although I can find it happening on more than one occasion:

10 Feb - 09:01:00.996 - Job executing
10 Feb - 09:01:00.001 - Job executing

So it runs it at 09:01:00.001 but then right again at .996. Without understanding the code-behind I'm having trouble understanding why this could be happening. Is this self-inflicted?

**Comment by jamesmh** [comment]
Ya it's potentially the library. Long story short, introducing the ability to configure "seconds" scheduling has introduced this. This is something that could be fixed - but essentially comes from the .NET `Timer` class not being 100% capable of polling exactly every 1 second, for example.

Anyways, I think this is legit and the opposite can happen too where a given second is actually missing as a "tick". The timer might have run at 9:00:00:999 and then at 9:00:02:000 - which could come from high cpu usage, IO, etc. 

Anyways, something that I've had in mind to fix for a while 👍

**Comment by smithb115** [comment]
Thank you for the quick response! I'm glad that I'm not going crazy and your explanation was helpful for me to understand what is probably going on here. I'll just have to resolve it a different way. You've made a really awesome library here, definitely a big fan!

**Comment by jamesmh** [comment]
Thanks Brent!
