### ISSUE TITLE
Question: How do you un-schedule invocables?

### ISSUE THREAD

**Issue by bmildh** [jamesmh/coravel#216]
Hello!

Like the title says, how do you go about to un-schedule some invocable that's been scheduled, let's say, EveryHour? 

I have seen the ICancellableInvocable. I have it implemented on my Invocable, but not sure how to use it? Where does the TokenSource come from? Don't you need that in order to set the CancellationToken?

/Regards

**Comment by jamesmh** [comment]
There's no supported public API (might be worth exposing it explicitly since many have asked about this...).

[Check out this closed issue](https://github.com/jamesmh/coravel/issues/77).

**Comment by jacoviza** [comment]
Good to have found this thread. @jamesmh it should definitely be worth exposing this feature in public API. Please let us know when this is available.
