### ISSUE TITLE
Can't stop windows service because of Coravel

### ISSUE THREAD

**Issue by EtkaBo** [jamesmh/coravel#221]
**Describe the bug**
![image](https://user-images.githubusercontent.com/28845040/111493242-60999500-870b-11eb-91e1-30f55aa81f71.png)

I think _scheduler.IsRunning is never getting set to false, that's why it just keeps looping in the while loop. Because when I try to stop my service, I see the warning log and windows service's status gets stuck in "Stopping" status

**Affected Coravel Feature**
I think _scheduler.IsRunning is not getting set to false properly. I have jobs that run every minute maybe that's why

**Expected behaviour**
If I need to stop my windows service than I should be able to, I think we can either configure Coravel to skip StopAsync method all together if I don't want to, or some sort of escape from while loop if it's been waiting a lot.

But most of the time I need an immediate stop if I want to stop it, so I think I'd choose a configuration to skip StopAsync method all together

**Comment by jamesmh** [comment]
This is where implementing `Coravel.Invocable.ICancellableInvocable` on an invocable class can help you (see [docs for more](https://docs.coravel.net/Scheduler/#invocables)). If there's a loop, for example, where you're making API or DB requests to do stuff, then you can check the cancellation token after each loop iteration (or even more fine-grained) to see if the app is trying to close, and then manually skip the rest of the method.

**Comment by EtkaBo** [comment]
I don't even think ICancellableInvocable's cancellation token even do anything in this case. I'll explain my discovery. 

I think what happens is when still there's a Coravel task processing(Scheduler.RunWorkersAt is processing) and at the same time windows service stop gets called, it stops the processing requests first and then it calls IHostedService.StopAsync. And then since processing requests are stopped _schedulerIterationsActiveCount field is stuck in a number that is greater than 0. That's why it just loops and loops inside of the while loop forever because it won't ever get back to 0 because processing requests were terminated.

To back up what I'm saying, this is the code of .net core

![image](https://user-images.githubusercontent.com/28845040/112357008-24cb7600-8c9d-11eb-889d-961666907fcf.png)

If you look at line 329 you'll see Server.StopAsync method get's called before IHostedService.StopAsync. And what does Server.StopAsync do is it "Stops processing requests and shut down the server, gracefully if possible."

![image](https://user-images.githubusercontent.com/28845040/112357404-7e33a500-8c9d-11eb-8269-3bcf8b551bc2.png)

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.server.iserver.stopasync?view=aspnetcore-5.0


So before it even calls your IHostedService.StopAsync at line 335, it probably already terminated the other processing requests that's why it's stuck in the while loop

**Comment by Blinke** [comment]
That explanation doesn't make much sense to me. Surely `IServer.StopAsync` just means the server will stop processing incoming requests, not somehow terminate all running tasks? The only reason `_schedulerIterationsActiveCount` could stay above 0 is if one of the tasks in `RunWorkersAt` hasn't completed yet. 

Are still seeing this behavior when using the `ICancellableInvocable`?

**Comment by EtkaBo** [comment]
I haven't checked `IServer.StopAsync` 's implementation yet, checking it right now. 

I'm pretty sure that processing requests getting terminated that's why `_schedulerIterationsActiveCount`  gets stuck above 0. I have logs all over the place in application and I also added a log inside the while loop like this: 

![image](https://user-images.githubusercontent.com/28845040/112369950-cdcc9d80-8caa-11eb-9c63-c33014dd85a0.png)

Whenever trying to stop the service all the other logs in the application stops, web server becomes unavailable, and the only thing I see is coravel preventing service from stopping inside of the while loop.

Last time I tried stopping it was an hour ago, so it's been looping for an hour as you can see:

![image](https://user-images.githubusercontent.com/28845040/112370149-09676780-8cab-11eb-9250-c8093ffc3310.png)

![image](https://user-images.githubusercontent.com/28845040/112370093-fa80b500-8caa-11eb-9f40-8d4ff4275228.png)

and there are no logs in between. I have no process that takes more than hour, even if it does, there will be some logs, but there's no logs for an hour except the while loop's log. Also can't hit the service's endpoints anymore, that also supports what I'm saying, it has terminated everything by the time it got to StopAsync method

**Comment by Blinke** [comment]
I had a look at the implementation of `IServer.StopAsync` in `IISHttpServer` [here](https://github.com/dotnet/aspnetcore/blob/493d0bf8c6432d0ea4f67238557d690c17932875/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs#L105).

![image](https://user-images.githubusercontent.com/7304557/112373871-bb218b00-8ce1-11eb-8bf1-32b0260e0f41.png)

It just stops processing incoming request, that's it. Whatever it is that keeps the scheduler running it's not related to this. Without seeing any of your code it's really hard to tell what the issue might be. Are you able to produce a small sample that can replicate the issue?

**Comment by jamesmh** [comment]
Yes, would be very helpful to see the code for the invocable / task that's causing issues :)

**Comment by jamesmh** [comment]
@EtkaBo do you still need help on this?
