### ISSUE TITLE
Doc Page Problem with Invocables

### ISSUE THREAD

**Issue by pkellner** [jamesmh/coravel#231]
Following the docs here:

https://docs.coravel.net/Invocables/

It starts out with code like this:

```
scheduler.Schedule<ReIndexDatabase>()
      .DailyAtHour(01)
      .Weekday();
```

No where does it say where this code goes and where scheduler is defined.  I think (but not sure, just trying now) that this is what I need to do.

```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.ApplicationServices.UseScheduler(scheduler =>
            {
                scheduler
                    .Schedule<ReIndexDatabase>().DailyAtHour(01)
      .Weekday();
            });
```

When I try this, My ReIndexDatabase IInvocable never gets called so I'm still not understanding something.

**Comment by pkellner** [comment]
Also, not to discount that I'm not always the sharpest pencil in the cup.

In this same section I could not get the ReIndexDatabase invcocable to run. I finally figure out it was because I was not doing the addTransient.  That is, in the screen shot below, it was not obvious to me I had to do the addTransient for ReIndexDatabase.

![2021-06-01_16-57-19](https://user-images.githubusercontent.com/241170/120404193-a9b8b880-c2fa-11eb-8e46-a7ba4dc2d017.png)

**Comment by jamesmh** [comment]
I added a little extra sentence under the "manually" no. 3 section to address this.
