### ISSUE TITLE
invoking coravel job manually with arguments

### ISSUE THREAD

**Issue by Kawthar-Ebrahim** [jamesmh/coravel#235]
Hello... I am working on a project that needs to invoke Coravel job manually once a specific event occurred. I have already defined the invocable class but I the challenge I am facing right is I need to invoke with arguments .. and it seems that Coravel invocable classes cant accept parameters 

I thought about using constructor injection but this prevents me from using the DI container.

I saw some examples of queuing/scheduling invocable class with arguments but they don't help me since in my case I am invoking the invocable manually.

Appreciate any help.

**Comment by Blinke** [comment]
Coravel invocables can absolutely use parameters. If you have access to the service provider, you can instantiate the invocable the same way Coravel does by using the ActivatorUtilities class. See [here](https://github.com/jamesmh/coravel/blob/751d1c39fad0f65b8201d30b64a3b25053818e6d/Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs#L122).

**Comment by jamesmh** [comment]
One of the benefits of invocable classes is that they are just classes....you make them. So you can do whatever you want. For example, if in one part of your application you want to invoke it manually, that's fine.

Perhaps the easiest ways of doing this is with a factory function:

```csharp
public class SomeJob: IInvocable
{

   private int someParam;
   private SomeDIClass someClass;
   
   // This constructor is used by Coravel
  public SomeJob(SomeDIClass  someClass, int someParam)
  {
    this.someClass = someClass;
    this.someParam = someParam;
  }
  
  // This is a static factory function that you can use wherever you want
   public static SomeJob Make(SomeDIClass someClass, int someParam)
   {
      return new SomeJob(someClass, someParam);
   }
}


// Elsewhere in your application...

var job = SomeJob.Make(someClass, 5);
await job.Invoke();
```

Or you could do what @Blinke  suggested 😊 Either should work 👍

**Comment by Kawthar-Ebrahim** [comment]
@jamesmh Thank you for your response but I am not sure if it would help.
- this means that the DI classes (e.g. logger, contextAccessor, ...etc) should be sent from my application when calling the factory function?
- this means as well that the parameters should define in the constructor? please find my code and the error I am getting when doing this.

_public SendConfirmSMS(List<Request> requests, string customerId, string mobileNo,
            LoanSkipContext context, ISMS SMSService, IHttpContextAccessor contextAccessor)
        {
            _skipRecords = skipRecords;
            _customerId = customerId;
            _mobileNo= mobileNo;
            _context = context;
            _SMSService = SMSService;
            _contextAccessor = contextAccessor;
        }
        public Task Invoke()
        {
            _logger.LogInformation("Send Confirm SMS job is running");
            SendConfiramSMS();
            return Task.CompletedTask;
        }
        public static SendConfirmSMS Make(List<Request> requests, string customerId, string mobileNo,
            LoanSkipContext context, ISMS SMSService, IHttpContextAccessor contextAccessor)
        {
            return new SendConfirmSMS(requests, customerId, mobileNo,
             context, SMSService, contextAccessor);
        }_

I am getting this error when running the app 

': Unable to resolve service for type 'System.Collections.Generic.List`1[LoanSkip.Models.Request]' while attempting to activate 'LoanSkip.Invocable.SendConfirmSMS'.)'

also, I am not sure why we are using the make function while we are defining the parameters in the constructor in all the cases,, can we initialize the job by the constructor directly with the make function?

Thank you very much.

**Comment by jamesmh** [comment]
> this means that the DI classes (e.g. logger, contextAccessor, ...etc) should be sent from my application when calling the factory function?

Yes, if you decide to use a factory function then you'll need to have your DI objects injected somewhere else. If you are trying to manually run this job from a controller, for example, then your DI objects should be injected via the controller's constructor. Then, you'll have all the objects that your job requires (plus the parameters that you can manually define too).

> this means as well that the parameters should define in the constructor? please find my code and the error I am getting when doing this.

Yes - if you are using Coravel's scheduler to schedule a job that has additional parameters, like in your case, then you can [use this](https://docs.coravel.net/Scheduler/#scheduling-with-additional-parameters). Note what this part of the documentation says:

> Ensure that any parameters to be injected via dependency injection are listed first in your constructor arguments

I suspect that your constructor argument aren't in this order - that's potentially the error you are getting.

**Comment by Kawthar-Ebrahim** [comment]
> 
> I suspect that your constructor argument aren't in this order - that's potentially the error you are getting.

Thanks @jamesmh for your reply. I have modified the order but same error occured. 

`': Unable to resolve service for type 'the type of the first additional parameter' while attempting to activate 'project.Invocable.SendConfirmSMS'.)'
`
I am not invoking the invocable by scheduler, I am only invoking it manually once a specific event occurred. The exception appeared directly once the app runs before even calling the method. By the way I am adding the job in the startup as follow : 
`services.AddTransient<SendConfirmSMS>();`
I think what happening is the program trying to identify the parameters in the constructor at the startup before calling the factory function. I am not sure how this can be solved.

**Comment by jamesmh** [comment]
When you say `I am only invoking it manually once a specific event occurred.` could you show me how you are doing this with a code sample?
