### ISSUE TITLE
cron for every hour（* */1 * * *） cannot work

### ISSUE THREAD

**Issue by cailin0630** [jamesmh/coravel#250]
cron for every hour（* */1 * * *） ，actually runs every minute

**Comment by jamesmh** [comment]
Why don't you use `1` instead of `*/1`?

**Comment by cailin0630** [comment]
> Why don't you use `1` instead of `*/1`?

According to unit test（[https://github.com/jamesmh/coravel/blob/master/Src/UnitTests/CoravelUnitTests/Scheduling/CronTests/CronExpressionTests.cs](https://github.com/jamesmh/coravel/blob/master/Src/UnitTests/CoravelUnitTests/Scheduling/CronTests/CronExpressionTests.cs)），The hourly expression I understand is （* */1 * * *）

**Comment by jamesmh** [comment]
Yes, that is something that should be fixed 👍 In the meantime, using `1` would work right?

**Comment by cailin0630** [comment]
> Sorry, I got a bit mixed up 😄
> 
> `* */1 * * *` is supposed to be every minute. You would have to make the first `*` into `0`.
> 
> `0 */1 * * *` would represent every hour at minute "00". If the first value is set to `*` then it means run every minute.
> 
> Likewise, this should run every hour also:
> 
> `00 * * * *`
> 
> Let me know if either of these work out for you (it's what works under the covers for Coravel's helper methods).

thanks，problem solved
