### ISSUE TITLE
RunOnceAtStart not working

### ISSUE THREAD

**Issue by Rluxx** [jamesmh/coravel#257]
Hi,

I tried to use the RunOnceAtStart() feature that has been introduced with 4.0.5.
It seems on startup it does not trigger the invoke.

To make sure it was not my code breaking it, I tried it with the WorkerServiceScheduler sample.
The only time I do manage to trigger it immediately is when I use EverySeconds(x).
When I try to combine it with something else it will not trigger on startup.

I would expect this to trigger immediately.

**Comment by jamesmh** [comment]
I'll have a look and get back to you :)

**Comment by jamesmh** [comment]
FYI extra comments in #181

**Comment by GagaOvO** [comment]
There's still a bug on RunOnceAtStart() with the latest version

**Comment by jamesmh** [comment]
@GagaOvO what's the behavior you're experiencing specifically?
