### ISSUE TITLE
Publish XML documentation with NuGet package

### ISSUE THREAD

**Issue by felpel** [jamesmh/coravel#265]
Hi,

First of all, thank you for this great library!

Would it be possible to produce and publish the XML documentation as part of Coravel's NuGet package?

The online documentation is really helpful, but it could help developers to see documentation within the IDE itself (e.g. Intellisense), preventing back & forth between your browser and your IDE.

Also, it would also highlight which part of the public API that is not yet documented and that could be.

Here is a reference to a [StackOverflow question](https://stackoverflow.com/a/58165750) which explains how to do it.

**Comment by felpel** [comment]
Hey @jamesmh, just a quick follow-up to let you know that it works like a charm, see for yourself:

### Before
![image](https://user-images.githubusercontent.com/5000004/164947942-f918e8f8-58cb-4a1b-8cd4-c65022698381.png)

### After
![image](https://user-images.githubusercontent.com/5000004/164947944-2391e653-7e14-493f-b54f-c699556fbf5f.png)

**Comment by jamesmh** [comment]
Nice nice - thanks for the help @felpel! Great improvements here 🤘
