### ISSUE TITLE
[Docs] RunOnceAtStart docs seem to be incorrect

### ISSUE THREAD

**Issue by Eric-Bonneau** [jamesmh/coravel#272]
Hi,

I'm not sure what issue type to open for this, but I may have found an issue with the documentation found [here](https://docs.coravel.net/scheduler/#force-run-a-task-at-app-startup).

**Describe the bug**
The example shows:

```csharp
scheduler.Schedule<CacheSomeStuff>()
    .RunOnceAtStart()
    .Hourly()
    .Weekday();
```

When I try to do the same, it doesn't seem like the method is available on `IScheduleInterval`:

![image](https://user-images.githubusercontent.com/13652737/148577234-a1bba7fc-a222-489c-ad20-9a29638212b6.png)

**Affected Coravel Feature**
Scheduling, specifically the run once at start functionality.

**Expected behaviour**
It seems like `RunOnceAtStart` is only available as a method on `IScheduledEventConfiguration` and the example should therefore be:

```csharp
scheduler.Schedule<CacheSomeStuff>()
    .Hourly()
    .Weekday()
    .RunOnceAtStart();
```

**Side note**

Thanks a lot for all your hard work. This package has made running scheduled jobs a breeze!

**Comment by jamesmh** [comment]
Thanks Eric!  Good find 😉

**Comment by Xenovore** [comment]
I can confirm that the docs are still wrong.

But yeah, nice job on a great library! Thanks for creating this!

**Comment by jamesmh** [comment]
This should be fixed now (or whenever the docs build ina few min lol)

**Comment by 545867454** [comment]
hi, the RunOnceAtStart() method is present.  but no start Job-4.0.5 version.Need to upgrade to 4.1.0 version?

**Comment by jamesmh** [comment]
Don't remember... I think there was an issue in a past version. Try 4.1.0 and see if it fixes it 😃
