### ISSUE TITLE
Link license to NuGet package

### ISSUE THREAD

**Issue by felpel** [jamesmh/coravel#281]
Hi,

We're using [Black Duck](https://www.blackducksoftware.com/) to monitor our various dependencies and we're receiving some warnings for [your package](https://www.nuget.org/packages/Coravel/4.1.0) regarding a missing license. I believe this is due to the fact that we're not able to see the license in NuGet. I know that you've included a `LICENSE` file, but would it be possible to include this information when the package is updated on NuGet?

I'm not sure if you're using a .nuspec file, but it seems like you could include MIT in [the license attribute](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license).

Please let me know if there is anything I can help with.

Thanks a lot 😎

**Comment by jamesmh** [comment]
This should be fixed. Re-open if there are any issues, etc. Thanks for the help @felpel! 🚀
