### ISSUE TITLE
Runtime error on valid (non-standard) cron expressions

### ISSUE THREAD

**Issue by verback2308** [jamesmh/coravel#292]
**Describe the bug**
Using of cron expression like this "1/1 * * * *" throws an exception without any chance to handle that leads to a fatal stop of the application or service.
Reproduces in a console app and background service.
This type of cron expression passes the validation and is added to the scheduler. But when it has to execute - the whole runtime crashes.

`ISchedulerConfiguration OnError(Action<Exception> onError);` can't handle it.
Whole wrapping of Program.cs content into try-catch can't handle too.

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1249954/165520826-e99ce2e0-1322-4463-99bd-b152e5077edb.png">

**Affected Coravel Feature**
Scheduling

**Expected behavior**
The expected result should be the same as for nonvalid cron expressions: exception while scheduling.

@jamesmh

**Comment by jamesmh** [comment]
Thanks for finding this. Will check it out 👍

**Comment by jamesmh** [comment]
This should be fixed in 4.2.2. Now you'll get an exception immediately when scheduling a malformed cron expression.
