### ISSUE TITLE
Using an ICancellableInvocable in a dotnet 6 program

### ISSUE THREAD

**Issue by myddraall** [jamesmh/coravel#295]
I have created a sample invokable, and when I attempt to stop the console application it appears the Cancellation is not honored.  
I am setting the host up as follows: 

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services
            .AddLogging(x =>
            {
                x.AddConsole();
            })            
            .AddTransient\<SampleInvokable\>()
            .AddScheduler();
    })
    .Build();

host.Services.UseScheduler(scheduler =>
{
    scheduler.ScheduleAsync(async () =>
    {
        var logger = host.Services.GetService<ILogger<Program>>();
        logger.LogInformation("Test");
        var sample = host.Services.GetService<SampleInvokable>();
        await sample.DoSomething();
    })
    .EveryFifteenSeconds();
});

This triggers fine

the sample invokable is implemented as follows:
internal class SampleInvokable : ICancellableInvocable
    {
        
        public CancellationToken CancellationToken { get; set; }
        public ILogger<SampleInvokable> _logger { get; set; }

        public SampleInvokable(ILogger<SampleInvokable> logger)
        {
            _logger = logger;
        }

        public async Task DoSomething()
        {
            CancellationToken.ThrowIfCancellationRequested();
                        
            _logger.LogInformation($"Starting, 15 second delay is started");
            await Task.Delay(TimeSpan.FromSeconds(15));
            _logger.LogInformation($"Cancellation token was set to request cancellation: {CancellationToken.IsCancellationRequested}");
            await Task.CompletedTask;
        }
    }

When I run the application, and see the log line "Starting, 15 second delay is started" I hit ctrl-c to get the service to stop, and when I do, it waits the rest of the 15 seconds, and then shuts down.  
The console logs look like the following:
info: Program[0]
      Test
info: Project.SampleInvokable[0]
      Starting, 15 second delay is started
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
warn: Coravel.Scheduling.HostedService.SchedulerHost[0]
      Coravel's Scheduling service is attempting to close but there are tasks still running. App closing (in background) will be prevented until all tasks are completed.
info: Project.SampleInvokable[0]
      Cancellation token was set to request cancellation: False
info: Coravel.Scheduling.HostedService.SchedulerHost[0]
      Coravel's Scheduling service is now stopped.

D:\Src\ProjectFolder\bin\Debug\net6.0\Project.exe (process 63736) exited with code 0.

Can you help identify why the cancellation token is not being set to request cancellation, and waiting the full duration?

**Comment by jamesmh** [comment]
Try using:

```csharp
scheduler.Schedule<SampleInvokable>()
   .EveryFifteenSeconds();
```

👍

**Comment by myddraall** [comment]
Thank you!  I had to add the cancellation token to the Task.Delay to get my example to work, if anyone comes behind and wants to follow along, but it stopped immediately on ctrl+c.  I appreciate your help!
