### ISSUE TITLE
Do works before app shut down?

### ISSUE THREAD

**Issue by ed555009** [jamesmh/coravel#298]
I am trying to use Covavel within a worker service project and it works like a charm, but I need to run a piece code to clean up files generated during tasks.

With a `BackgroundService` class I can do:
```
public override async Task StopAsync(CancellationToken cancellationToken)
{
	// do stuff here

	await base.StopAsync(cancellationToken);
}
```

I see logs below when Ctrl-c to exit app, so I guess there are somewhere I can put codes in an `IInvocable` class to achieve this just like `StopAsync()`?
```
[21:59:52 INF] Application is shutting down...
[21:59:52 INF] Coravel's Scheduling service is now stopped.
```

I have been through the official docs but did not find any.

**Comment by jamesmh** [comment]
There's no specific way with Coravel to run specific code on app shutdown, but if you have a scheduled job that's running and the application goes to shutdown while you have work in-progress, then Coravel is smart enough to force the shutdown to wait until that work is done.

Let me know if you need more help 👍
