### ISSUE TITLE
When() Fluent Restriction

### ISSUE THREAD

**Issue by jamesmh** [jamesmh/coravel#30]
User's should have an additional method available when adding restrictions to their scheduled events.

The syntax would look like this:

```
scheduler.Schedule(() => //.... do the stufff )
    .EveryMinute()
    .Monday()
    .When(() => someValue = false);
```

The scheduled event will not fire if `When` returns false.

Internally this should be a collection of `Func<Bool>` , in the event that the user wants to call `When` multiple times with different conditions etc.

For now, this issue will be pending the next release as it contains an overhaul to the scheduling internals.

**Comment by papakaliati** [comment]
Reporting for duty.

**Comment by jamesmh** [comment]
Hmm can't see you in the list. O well. I'll let you know when things are ready to go 👍

**Comment by jamesmh** [comment]
@papakaliati - create a new branch off the current master branch (a nice new clean one). You'll see that the scheduler is quite different now.

So, basically, add a new method to `IScheduledEventConfiguration` :

`IScheduledEventConfiguration When(Func<Task> predicate);`

Internally, the `ScheduledEvent` will implement this new method. 

Just add one private field to hold `Func<Task>` (so only one predicate is ever used).

Put the check in `InvokeScheduledEvent` as the first thing. If when is not null, and it returns false, then `return Task.CompletedTask` right away.

Hopefully that make sense?

Thanks for the help!

**Comment by papakaliati** [comment]
Unless I am missing something, shouldn’t it be Func<bool> ?

**Comment by jamesmh** [comment]
lol Ya, actually I meant `Func<Task<bool>>`. 

So that call should be awaited when being checked in the `ScheduledEvent` .

Sorry about that!

**Comment by papakaliati** [comment]
Sooo some thoughts. Func<Task<bool>>  is of course the  logical implementation, but then the only way to pass a non Task method, becomes  from  : 

.When(Test)
.When(async () => Test())

,(Test is bool Test() => … )

The fun actually starts when you wanna add two When, one with Func<Task<bool>> and the other Func<bool>
When trying to pass When(Test) it gives an ambigious method call error.

**Comment by papakaliati** [comment]
The most elegant solution I can think of, is to make the interface with 

 IScheduledEventConfiguration When(Task<bool> predicate);

 IScheduledEventConfiguration When(Func<bool> predicate); 

And then transform both on ScheduledEvent to  Func<Task<bool>>  so to make it simple to check that  only one  
Is alive.

With Task<bool> and Func<bool> invocation is actually more elegant :
 .When(filter) for bool and .When(filterAsync()) for Task<bool>,

**Comment by jamesmh** [comment]
I think just using `Func<Task<bool>>` is fine. 

If there's a time when the user doesn't need to use an async method / await, they should be able to use `return Task.FromResult(true);`

So some good unit tests you could build are something like:

```c#
bool shouldRun = true;

scheduler
    .Schedule(someAction)
    .When(() => return Task.FromResult(shouldRun)); 
```

And maybe another one something like this:

```c#
Func<Task<bool>> shouldRun = () => Task.FromResult(true);

scheduler
    .Schedule(someAction)
    .When(shouldRun); 
```

And to include awaiting:

```c#
Func<Task<bool>> shouldRun = async () =>
{
     await Task.Delay(0);
     return true;
}

scheduler
    .Schedule(someAction)
    .When(shouldRun); 
```

And of course, some cases when "shouldRun" is false and make sure the task didn't run. Those are just off the top of my head... hopefully they ok lol.

Thanks @papakaliati !

**Comment by papakaliati** [comment]
Think i covered all of those cases already and uploaded already.
Additionally having when with both Task<bool> and Func<bool> plays nice
with each other.

**Comment by jamesmh** [comment]
Done at #32

**Comment by papakaliati** [comment]
Cheers mate, thanks 👍
