### ISSUE TITLE
Add global from to Mailing docs

### ISSUE THREAD

**Issue by lwestfall** [jamesmh/coravel#320]
**Describe the solution you'd like**
The documentation (great as it is) is missing details about the usage of `globalFrom` in service registration which would've sped up development for my use case. After digging into the source code I have a good handle on it. If you'd like I'd be happy to take a stab at a PR!

**Comment by jamesmh** [comment]
Cool! Would love the help. You can have a look at this file (the docs for the mailer):

https://github.com/jamesmh/coravel/blob/master/DocsV2/docs/Mailing/README.md

**Comment by lwestfall** [comment]
Sounds good!

One quick question, I noticed that calling `.From("someone@somewhere.com")` in `Build()` doesn't seem to override the globalFrom address. Would it be better if it did? In my mind it seems like globalFrom should sort of be treated as a "default" from address, which can be overridden when building (maybe someone wants to conditionally override the from address, or certain Mailable implementations should have a different From address, etc).

I know this is a little more involved than just the docs so if it's something you're interested in I'll get this into a separate issue and PR.

**Comment by jamesmh** [comment]
Ya I think that makes sense to override the global from if you call `From()` 👍

**Comment by jamesmh** [comment]
This is fixed - thanks!
