### ISSUE TITLE
How much schedule Tasks could be run for an application?

### ISSUE THREAD

**Issue by codingkondi** [jamesmh/coravel#322]
Hi 
I have an .NET WebAPI with Coravel , and it could add schedule task by ScheduleWithParams method.
when my user wanna schedule their api ,they call my api and the service will use ScheduleWithParams to add schedule task.
if they wanna remove schedule ,I just use TryUnschedule for cancel their schedule.

however , I have no idea how much schedule task( different thread? ) I could add in the application by coravel?

**Comment by jamesmh** [comment]
That really depends on your system's resources - CPU, memory, etc. Something you would have to test out yourself.
