### ISSUE TITLE
Is it possible to run the tasks one after the other?

### ISSUE THREAD

**Issue by alandecastros** [jamesmh/coravel#325]
In this code you're runnning WhenAll making the tasks run in parallel, right?

https://github.com/jamesmh/coravel/blob/4a1b91d1f905ac45c572994cac46ab8d25aff30f/Src/Coravel/Queuing/Queue.cs#L102

I'm running into some issues with database max pool size limit (lots of tasks running at the same time) and wanted to know what you think about creating an option to run tasks one by one? Or am I missing something?

Regards

**Comment by jamesmh** [comment]
Yes, that's an issue that can come up. This used to be the way Coravel worked, but changed it for throughput reasons. I not sure adding this as an option should be a concern of Coravel proper....

There are other ways around this specific issue.

# 1
You create a static (or DI injected) class that handles creating all your DB connections. This will pool or just limit how many connections can be used at a given time.

Different interfaces could exist for something like this:

```csharp
var sqlConnection = await connectionPool.GetOpenConnectionAsync();
```

Or

```csharp
await connectionPool.WithSqlConnection(async sqlConnection => {
    await sqlConnetion.ExecuteAsync(SQLString_const);
});
```

Under the covers, you would probably use a semaphore to limit how many actions can occur concurrently.

# 2

Another consideration: it might be that your code could be issuing too many SQL connections and that could be optimized.

# 3

Or, if your code gets a specific exception, you could handle that specific exception and retry in X milliseconds (with backoff, etc.) Many use something like Poly for that.

# 4
Or, it could be a legit issue where there's some bad code that's not releasing DB connections efficiently. Here's a SO example: https://stackoverflow.com/questions/49748789/max-connection-pool-reached

**Comment by alandecastros** [comment]
Thanks @jamesmh ! I'll see my options here!

Regards
