### ISSUE TITLE
Task scheduling does not work in .NET Maui 

### ISSUE THREAD

**Issue by ahmed527** [jamesmh/coravel#334]
**Describe the bug**
Since Maui (previously Xamarin) is part of .NET platform, I expected Coravel Task Scheduling to work, but it is not.  I tried different combinations of the configuration options but still had the same outcome. The configuration is similar to a Web API configuration as below:

```
   public class MyFirstInvocable : IInvocable 
    {
        public Task Invoke()
        {
            Console.WriteLine("This is my first invocable!");
            return Task.CompletedTask;
        }
    } 
```

```
 builder.Services.AddScheduler();
        builder.Services.AddTransient<MyFirstInvocable>();
  
        var app = builder.Build();
 
        var provider = app.Services;
        provider.UseScheduler(scheduler =>
        {

            scheduler
              .Schedule<MyFirstInvocable>()
              .EverySeconds(2)
              .Weekday();
        });

```
**Affected Coravel Feature**
Scheduling

**Expected behaviour**
I expect the debugger hits my break point inside _MyFirstInvocable_ . I tried without invocable as well.

I appreciate any help.

Thank you

**Comment by jamesmh** [comment]
I don't think MAUI supports `BackgroundService` and `HostedService` so Coravel won't work. [See this open issue.](https://github.com/dotnet/maui/issues/2244)
