### ISSUE TITLE
Update Mailkit Version to 4.x.x

### ISSUE THREAD

**Issue by tidan-16** [jamesmh/coravel#349]
**Describe the solution you'd like**
Could we get an update of the Mailkit package? it does not support the version 4.x.x

**Describe alternatives you've considered**
I can use the version 2.5.1, but would prefer keeping things up to date.

Is it possible or no?

**Comment by jamesmh** [comment]
Mailer is not a priority right now for me (maintainer). Feel free to fix it and submit a PR if you feel you get lots of value from using the mailer + MailKit 4.x.x+ 👍
