### ISSUE TITLE
Separate packages?

### ISSUE THREAD

**Issue by anth12** [jamesmh/coravel#35]
Hi, I have been looking for task scheduler to run in asp.net core and this looks great. I am hesitant to install the nuget however due to dependencies I do not require.

Would you consider splitting Caching/Mail/Queuing/Scheduling into independent packages so that users can pick and chose their dependencies?

I wouldn't have minded installing the components I have no use for (Caching/Mail/Queuing), however the dependency on `Mailkit` is a show stopper for me.

**Comment by jamesmh** [comment]
I'm voting this on twitter - https://twitter.com/jamesmh_dev/status/1035487034679455744

You can try to get convince people there too ;)

**Comment by anth12** [comment]
@jamesmh great, I'm glad you are open to the idea. I think having a dedicated package for scheduling in particular would draw a lot more users as its a common requirement. Sure there are other solutions (hangfire, quartz etc.) but they are often quite large & hefty.

I have [made a start](https://github.com/anth12/coravel/tree/separate-mail) by refactoring Mail to it's own project. 

I get you would like to make it easy to setup everything without worrying about installing x packages, for this I would recommend the approach used by asp.net where they have a `.All` nuGet which has dependencies on all the various components.

**Comment by jamesmh** [comment]
The .All package is a good idea. I wouldn't suggest refactoring it yet since I haven't made any decisions ;)

**Comment by jamesmh** [comment]
The mailer is technically already in two packages, so I might just opt to put in the existing one etc. We'll see...

**Comment by jamesmh** [comment]
So at the very least I'll be combining the mailer + existing razor page projects into a new one (mailer).

I should be done sometime next week - I'll let you know!

**Comment by jamesmh** [comment]
Mailer is separate now. I opted to keep the other features together for now. Just easier for me to maintain and fits better with future plans. Let me know if everything works out or not.
