### ISSUE TITLE
NET8 Blazor   Winform   not  work

### ISSUE THREAD

**Issue by liujian1368928** [jamesmh/coravel#352]
i  do not  know why, my  webapi  is  good  ，but blazor is  bad .

**Comment by jamesmh** [comment]
.NET blazor doesn't support using `HostedServices` which Coravel requires. Others in the community have asked for this to be added/supported but MSFT so far hasn't moved forward on this: https://github.com/dotnet/aspnetcore/issues/7213.

There might be an opportunity to rig something up yourself based on this MR, but not officially supported -> https://github.com/dotnet/aspnetcore/issues/33537
