### ISSUE TITLE
Coravel.Pro Boilerplate fails to start

### ISSUE THREAD

**Issue by woutervanranst** [jamesmh/coravel#356]
I have no experience with Coravel and wanted to give the Pro (esp. the Dashboard) features a go to evaluate vs Hangfire/Quartz.
However I do not get it up and running.

I tried the VS2022 boilerplate examples for a aspnet core web api / aspnet core w razor / the ef6 sample from the docs and followed the [steps from the docs](https://www.docs.pro.coravel.net/Installation/) but i keep getting this issue

```
System.InvalidOperationException: 'No service for type 'Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand' has been registered.'
```
![image](https://github.com/jamesmh/coravel/assets/6490925/52cc4e0e-26a6-4d6f-9f5f-708fbd7d1072)

What am I missing here?

**Comment by jamesmh** [comment]
In `ConfigureServices()` did you call `services.AddCoravelPro(typeof(ApplicationDbContext));`?

This step is [here](https://www.docs.pro.coravel.net/Installation/#basic-configuration) in the docs. Let me know if that's the issue or not - thanks!

**Comment by jamesmh** [comment]
Closing - plz inform if still an issue. Thanks!
