### ISSUE TITLE
Smtp Mailer Does not add Reply To address

### ISSUE THREAD

**Issue by riex406** [jamesmh/coravel#357]
When sending email with the SMTP driver and adding a Reply-To address, no reply to email address is added to the sent email. This affects only the Coravel.Mailer

Expected behavior would be for a Reply-To: address be added to the sent email and when replied to defaults to the specified email address. When using the FileLog diver there is a Reply-To line produced, just not with the current SMTP driver.

**Comment by riex406** [comment]
I forked this and added the Reply To logic to the SMTP Mailer implementation.  I don't contribute much to repositories, should I make a unit test for this change before submitting a pull request?

**Comment by jamesmh** [comment]
That would great - take a look at the existing tests for an idea 👍 Thanks!

**Comment by riex406** [comment]
Thanks for merging this, I really appreciate it.  I did notice that I didn't update the version number on the Coravel.Mailer package so it also didn't update NuGet.  Is that something I should have included in my pull request?

**Comment by jamesmh** [comment]
@riex406 I'll be updating that separately and deploying a new version shortly. Thanks! 🙂

**Comment by jamesmh** [comment]
This is included in `Coravel.Mailer version 5.0.1`
