### ISSUE TITLE
Is Coravel good fit for Blazor Server?

### ISSUE THREAD

**Issue by urza** [jamesmh/coravel#369]
Hi, coming from Nicks video about this library, it looks really good, I like how focused and minimal it is. I am interested mostly in scheduler and mailer.

However I noticed some issues here mention having problem with Blazor e.g. https://github.com/jamesmh/coravel/issues/352

So I wanted to ask if it is recommended to use Coravel  in Blazor Server apps?

Thanks

**Comment by jamesmh** [comment]
Unfortunately Microsoft has decided to not support `HostedService` from a blazor application. As mentioned in #352, there might be some work around but it is not supported in any "official" way 🤷‍♀️.

**Comment by urza** [comment]
What exactly would that prevent or break with Coravel on Blazor?

I tried a little experiment with blazor on .net 8 and it seems to be working, at least this simple test:

Blazor with Server Inveractivity:
Program.cs:
![image](https://github.com/jamesmh/coravel/assets/189804/ad95c0d1-46cc-449b-b696-38dec26de2f8)

Result:
![image](https://github.com/jamesmh/coravel/assets/189804/ba86f021-b5bc-477f-b8cf-7fb8743f2166)

**Comment by jamesmh** [comment]
I'm not  that familiar with the different Blazor models, but I using Coravel from a web server context should work. But, if you are trying to use it inside, let's say, a blazor component -> I think that's where things might break down.

It may be that using a server render mode fixes this too, but I don't know. It's not something that I've tested.

So as long as coravel is used by the web/backend server code then you should be okay. But using Coravel _within blazor components_ - not sure how far you will get.

**Comment by urza** [comment]
Got it thanks. I will try some experiments with scheduler from blazor pages / components and will update here if I encounter any problems.
