### ISSUE TITLE
Turn off logging "Coravel's scheduler is behind"

### ISSUE THREAD

**Issue by looc** [jamesmh/coravel#391]
Hi

If there is not a way (that i can not find) to remove the message "[Coravel.Scheduling.HostedService.SchedulerHost] Coravel's scheduler is behind 1 ticks and is catching-up to the current tick." from log please add one, its filling up my logs.

I am using Serilog as logger 

//Update
Removing Serilog.Extensions.Logging removes message but still maby it should not be a information message

**Comment by jamesmh** [comment]
Agree - will look to fix this soon.

**Comment by jamesmh** [comment]
Available in 5.0.4

**Comment by theofanis** [comment]
Ouch, went looking for this on a production system to validate some skips but it was nowhere to be found!

Then I found this issue 😅.

@jamesmh, why remove this entirely and not just change the log level? Maybe Warning or Debug? This would allow the flexibility to turn it off/on based on actual needs.

Any chance this can be reconsidered? 

Cheers and kudos for the splendid work on the library!

**Comment by theofanis** [comment]
@jamesmh kind ping about this one, any comment based on my comment above? Thank you!

**Comment by jamesmh** [comment]
Hey, will look into this and get back to you 👍

**Comment by jamesmh** [comment]
This should be available in the next few minutes via nuget `6.0.0`.

Check out the docs to see how to enable it: https://docs.coravel.net/Scheduler/#logging-tick-catch-up
