### ISSUE TITLE
Is there a support for Elastic Search APM in Coravel ?

### ISSUE THREAD

**Issue by srivastava-prashant** [jamesmh/coravel#398]
@jamesmh - 
We have an application in which we created a Web Scheduler using `Coravel`.  Where these Invocable are not run from Http protocol (i.e. via browser events). 
And, in our application we use Elastic APM (Application performance metrics).  But, when we try to use `ITracer `to create the transaction and use it. Then for some reason it does not shows up in Elastic Search APM side. Also, does not throw any error.

Per the documentation it seems elastic search does provide an option to use it for Background services. 
Now, since this `Coravel `is also kind of a background service. So, I wanted to know If- there is an option for us to use Elastic search in the `Invocables`.

**Here are few reference links -** 

https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-dotnet-net-core.html

https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html

![image](https://github.com/user-attachments/assets/8e32f592-c81b-47dc-b452-62242d91e984)

**Comment by jamesmh** [comment]
I'm not familiar with Elastic APM, but from the documentation it sounds like you need to use the [Elastic.Apm.NetCoreAll](https://www.nuget.org/packages/Elastic.Apm.NetCoreAll) package >

> This applies to both ASP.NET Core and to other .NET Core applications that depend on IHostBuilder, like [background tasks](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services). In this case, you need to reference the [Elastic.Apm.NetCoreAll](https://www.nuget.org/packages/Elastic.Apm.NetCoreAll) package.

Coravel is a `HostedService` so this would apply to Coravel. 👍
