### ISSUE TITLE
Queue time

### ISSUE THREAD

**Issue by P-de-Jong** [jamesmh/coravel#41]
Hi,

First of all, thanks for the great work. 👍 
But i was just wondering if there are any plans to make the 30 second queue time configurable.
Right now, debugging is a pain when you have to wait 30 seconds :)

**Comment by jamesmh** [comment]
Thanks man! There were no plans but that does sound like a good idea ;)

I'll assign this to myself and put it in the pipeline. 👍

**Comment by jamesmh** [comment]
On master + part of nuget 1.9.1
