### ISSUE TITLE
How to run a scheduled task in 5 minutes?

### ISSUE THREAD

**Issue by marc-weber1** [jamesmh/coravel#410]
**Describe the solution you'd like**
Currently, the only option I have for scheduling a task 5 minutes from now is .EveryFiveMinutes().Once(), which doesn't actually schedule a task for 5 minutes from now, or generating a cron string out of the current time; how do I schedule a job to execute 5 minutes from now, starting now?

Using the queue and a job starting with a Task.Delay(5000), with the setup I have now, takes much longer to run than 5 minutes; it doesn't seem like queued jobs have the same priority as scheduled ones

**Comment by jamesmh** [comment]
You could try something like this (might need some small adjustments, be the idea is here):

```csharp
var appStartTime = DateTime.UtcNow;

scheduler
    .Schedule<MyInvocable>()
    .EverySecond()
    .Once()
    .When(() => DateTime.UtcNow - appStartTime >= TimeSpan.FromMinutes(5));
```
