### ISSUE TITLE
Set DailyAt(10, 0), but it runs every day at 18:00pm

### ISSUE THREAD

**Issue by DreamTom** [jamesmh/coravel#418]
**Describe the bug**
scheduler.Schedule<CouponExpiredNotifyJob>().DailyAt(10, 0);
but it runs every day at 18:00pm
my server timezone is Etc/UTC

**Affected Coravel Feature**
Scheduling

**Expected behaviour**
runs every day at 10:00am

**Comment by jamesmh** [comment]
Have a look at the [documentation here.](https://docs.coravel.net/Scheduler/#zoned-schedules):

Something like this might do the trick:

```csharp
scheduler
   .Schedule()
   .DailyAt(10, 0)
   .Zoned(TimeZoneInfo.Local);
```

Just keep in mind that changing your server's TZ while coravel is running might mess up the schedule, etc. Let me know if that helps!

**Comment by DreamTom** [comment]
> Have a look at the [documentation here.](https://docs.coravel.net/Scheduler/#zoned-schedules):
> 
> Something like this might do the trick:
> 
> ```cs
> scheduler
>    .Schedule()
>    .DailyAt(10, 0)
>    .Zoned(TimeZoneInfo.Local);
> ```
> 
> Just keep in mind that changing your server's TZ while coravel is running might mess up the schedule, etc. Let me know if that helps!

thanks, it runs correctly
