### ISSUE TITLE
Exception thrown "Cron entry '00' is malformed." in Thai culture

### ISSUE THREAD

**Issue by storno77** [jamesmh/coravel#420]
**Describe the bug**
Hi, I get an exception when scheduling using eg. Hourly in Thai culture. Exception says:
    Coravel.Scheduling.Schedule.Cron.MalformedCronExpressionException : Cron entry '00' is malformed.

  **Stack Trace:** 
CronExpressionPart.CronExpressionPartIsDue(Int32 time, String expression, Int32 replaceZeroWith) line 52
CronExpressionPart.IsDue(Int32 time) line 29
CronExpression.IsMinuteDue(DateTime time) line 62
CronExpression.GuardExpressionIsValid() line 84
CronExpression.ctor(String expression) line 27
ScheduledEvent.Hourly() line 153
SchedulerHourlyTests.ValidHourly(Int32 day, Int32 hour, Int32 minute, Boolean shouldRun) line 54
--- End of stack trace from previous location ---

The behavior is reproducible in unittests:
```
public async Task ValidHourly(int day, int hour, int minute, bool shouldRun)
{
    CultureInfo th = new CultureInfo("th-TH", false);
    Thread.CurrentThread.CurrentCulture = th;

    var scheduler = new Scheduler(new InMemoryMutex(), new ServiceScopeFactoryStub(), new DispatcherStub());
    bool taskRan = false;

    scheduler.Schedule(() => taskRan = true).Hourly();

    await RunScheduledTasksFromDayHourMinutes(scheduler, day, hour, minute);

    Assert.Equal(shouldRun, taskRan);
}
```

**Affected Coravel Feature**
Scheduling

**Expected behaviour**
Using standard cron expression should not fail in Thai culture. Adding StringComparison.InvariantCulture to:
`var isDivisibleUnit = expression.IndexOf("*/", StringComparison.InvariantCulture) > -1;`
seems to fix the issue.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added StringComparison.InvariantCulture to the IndexOf method in CronExpressionPart to fix the issue with Thai culture. Also added a unit test to verify the fix.

You can review changes in this commit: https://github.com/mnmnk43434/jamesmh-coravel-420/commit/ba5745969aafbaec928d3ea99dcf4869ce2fe3c9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by storno77** [comment]
This could probably be enough as the fix.

**Comment by jamesmh** [comment]
This should be working in the latest version published to nuget. Thanks for the help!
