### ISSUE TITLE
Queuing feature not working?

### ISSUE THREAD

**Issue by IonRobu** [jamesmh/coravel#43]
I'm playing around queuing functionality a little bit, but no luck...
Steps:

1. Cloned Coravel repository
2. Add a Test console project, which reffers Coravel project
3. The code from Test console:

```
class Program
	{
		static void Main(string[] args)
		{
			var serviceProvider = new ServiceCollection()
				.AddQueue()
				.BuildServiceProvider();
			var queue = serviceProvider.GetRequiredService<IQueue>();
			queue.QueueTask(() =>
			{
				Console.WriteLine("This was queued!");//not firing
			});

			queue.QueueAsyncTask(async () => {
				await Task.Delay(1000);
				Console.WriteLine("This was queued async!");//not firing
			});

			serviceProvider
				.ConfigureQueue()
				.OnError(e =>
				{
					Console.WriteLine(e.Message);//not firing
				});
			Console.ReadKey();
		}
	}
```
The queued tasks not firing. I put a breakpoint in QueuingHost:StartAsync method, where queuing timer seems to be started, but not firing. Did I miss something?

**Comment by jamesmh** [comment]
I'll have a look and let you know :)

**Comment by IonRobu** [comment]
Great, so it was because of me :)
What is missing in my code sample?

**Comment by jamesmh** [comment]
So you'll need to you the .NET Core Host Builder to get console apps to work. I created an example [here](https://github.com/jamesmh/coravel/tree/master/Samples/HostBuilderWithQueue).

If you're not familiar with the host builder you might want to start [here](https://thinkrethink.net/2018/08/02/hostbuilder-ihost-ihostedserice-console-application/).

You'll probably need to create a Hosted Service to do whatever you need. Or, using the web host builder you could make a really slim service that exposes a few endpoints to do whatever you need.

Let me know if things work out!

**Comment by jamesmh** [comment]
PS That's  a quick and dirty example lol

**Comment by IonRobu** [comment]
I got it, thanks!
