### ISSUE TITLE
support netstandard2

### ISSUE THREAD

**Issue by abuassar** [jamesmh/coravel#46]
thanks for this wonderful library
would you please add support for .Net Standard 2.0
as it is used exclusively in the infrastructure layer and business layer
and .net core only used in web layer

**Comment by jamesmh** [comment]
Thank you! I originally built this as a .NET Core library since I was using features only available in .NET Core. 

These dependencies have been changed and "slimmed down" recently. I'll have to investigate if this is possible... I'll get back to you once I do that 👍

**Comment by abuassar** [comment]
if you split the interfaces into netstandard2 library and kept the implementation in netcore2 I may be able to reference it in my netstandard2 projects and inject the implementation from the netcore2 project.

**Comment by abuassar** [comment]
Hi @jamesmh,
Would you please provide a rough ETA for this feature?
So that I can plan when to integrate coravel with the system I'm currently working on.

Thanks for your hard work!

**Comment by jamesmh** [comment]
I've got a super busy week, so probably next week to be honest 😢

**Comment by jamesmh** [comment]
Ok had a bit of time tonight - didn't need that many changes! So version 2.0.0 is .NET Standard 2.0 compatible 🎉 🎈

**Comment by jamesmh** [comment]
@abuassar - 2.0.0 is indexed by NuGet and all ready for you.

Thanks for the great suggestion!

**Comment by abuassar** [comment]
@jamesmh fantastic, I'm already using it now 👍 

you rock, keep it up 👌
