### ISSUE TITLE
ICache Missing Has and Get

### ISSUE THREAD

**Issue by evanrobertson** [jamesmh/coravel#54]
A common pattern for caches are getting values without setting them and also checking if a key exists.

Similar to how [Laravel handles them.](https://laravel.com/docs/5.7/cache#retrieving-items-from-the-cache
)

I think it would be useful to provide both a `Get` method and a `Has` method.
```
Get<T>(string key);
Has(string key);
```

**Comment by jamesmh** [comment]
Great idea! I'll take a look at the PR hopefully within the next week ;)
I've got a lot of appointments this week 😢

**Comment by jamesmh** [comment]
@evanrobertson  P.S This is on the todo list - just been super busy with other priorities and "life" in general lol 👍

**Comment by tankerkiller125** [comment]
Any update on this? This is super common and in fact the reason I was originally looking to use Coravel, but because it doesn't have the "has" and "get" functions the cache is basically useless to me.

**Comment by jamesmh** [comment]
There's a PR that needs to be completed. I can push this into a higher priority among these other things on the list. 👍

**Comment by jamesmh** [comment]
Started working on this. 

Just FYI, the existing PR is not going to cut it. There are database drivers that exists now which are affected by any changes to the cache interface. So it'll involve releasing a few different nuget packages in order and implementing the changes in the in-memory driver, the SQL server one and the PostGreSQL driver.

**Comment by jamesmh** [comment]
Version 3.0.0 has `GetAsync` and `HasAsync`
