### ISSUE TITLE
Allow sub-minute scheduling

### ISSUE THREAD

**Issue by bortlip** [jamesmh/coravel#69]
Would you consider supporting sub-minute task scheduling?  Perhaps down to the second.

I'm writing a status checking application that polls other applications to make sure they are reachable.  We are using an asp net core application with an IHostedService that uses a timer to poll every X seconds.  We would like to switch to using Coravel, but are concerned about limiting how often we can poll to once a minute.

Thank you.

**Comment by jamesmh** [comment]
I've had that [asked by someone on twitter last week](https://twitter.com/vladmirboy/status/1071884612434083840)...

So, just off the top of my head, I'm thinking the usage would be the same:

```csharp
provider.UseScheduler(scheduler =>
{
    scheduler.Schedule<Poll3rdPartyApplications>()
    .EverySecond(); // THIS ONE
    .Weekday();
});
```

And adding methods like:

- `EverySecond()`
- `EveryFiveSeconds()`
- `EveryTenSeconds()`
- `EveryFifteenSeconds()`
- `EveryThirtySeconds()`

Would something like that work for you?

**Comment by jamesmh** [comment]
Cool!

I can't guarantee this will happen before the end of the year (with a new baby coming next week and typical end-of-year stuff 😉) but this seems like a great addition that will be next on my todo 👍

**Comment by bortlip** [comment]
I understand and thank you very much.  That would be great.

Congratulations and good luck with your baby!

**Comment by jamesmh** [comment]
**Wink Wink**

Working on it 😉

![image](https://user-images.githubusercontent.com/7213174/50019417-f8e2c580-ffa8-11e8-8e0a-ac83e7c5e6ec.png)

**Comment by jamesmh** [comment]
#71 in progress

**Comment by bortlip** [comment]
Awesome!

**Comment by jamesmh** [comment]
Alright - nuget package 2.3.0 is building right now and has the changes. Should be up soon (it's Saturday night anyways....) 

I cleaned-up the scheduler docs a little bit too so they should be easier to follow when trying to find the methods etc.

So, take a look at the scheduler docs and you'll see a few new methods there 😉

On a side-note, I'd be interested to know more about how you are/planning on using Coravel and some details about the company, if that's something you are willing/allowed to provide either here or through a DM.

I'm also looking for more companies to put up on the main repo's "Used By" section if that's something you'd be interested in.

Thanks again for the great suggestion! I usually only add new features if I feel it's necessary, something I personally need for projects using Coravel or if others have a need that does seem reasonable. So thanks for taking the initiative to let me know 👌

Let me know how things turn out!
