### ISSUE TITLE
Scheduler not working with invocable

### ISSUE THREAD

**Issue by soend** [jamesmh/coravel#70]
Hei, just starting up looking into how to use coravel in my project. Im finding that even when i follow the documentation coravel never executes schedule task when they are invocables.
What works: 
```
app.ApplicationServices.UseScheduler(scheduler =>
{
    scheduler.Schedule(() => Console.WriteLine("Scheduled task.")).EveryMinute();
});
```
What doesnt work:
```
app.ApplicationServices.UseScheduler(scheduler =>
{
    scheduler.Schedule<SendDailyStatsReport>().EveryMinute();
});
....
using System;
using System.Threading.Tasks;
using Coravel.Invocable;

namespace bot.Invocables
{
    public class SendDailyStatsReport : IInvocable
    {
        public async Task Invoke()
        {
            Console.WriteLine("Doing expensive calculation for 15 sec...");
            await Task.Delay(15000);
            Console.WriteLine("Expensive calculation done.");
        }
    }
}
```

If i debug the code and set breakpoint inside Invoke method then it is never hit.
Using latest nuget packet for coravel.

**Comment by jamesmh** [comment]
Did you add your invocable to the service provider? See [these instructions](https://github.com/jamesmh/coravel/blob/master/Docs/Invocables.md#creating-an-invocable)

Point number 3 in particular.

Basically, you need to do something like this:

In `ConfigureServices()`
```csharp
services.AddScoped<SendDailyStatsReport>();
```

Let me know if that works 👍

**Comment by soend** [comment]
Forgot to register invocable into service container...

**Comment by jamesmh** [comment]
haha! Ok awesome.

I will add some extra documention around that though since it may not be very obvious / explicit.

Thanks @soend !

**Comment by soend** [comment]
I followed the scheduler docs and didnt follow the link to invocables docs. Maybe add note to there would of helper. Thanks for fast reply!

**Comment by jamesmh** [comment]
Thanks for the great advice - let me know how things go overall with Coravel - I'd love to know 👍

**Comment by jamesmh** [comment]
I've got a new feature on the back-burner that would automatically configure the invocables etc. - so you wouldn't have to manually add them all. Prolly in the new year 😉
