### ISSUE TITLE
Cancellation support for queued Invokables

### ISSUE THREAD

**Issue by w-bonelli** [jamesmh/coravel#72]
Do you have anything like this in the pipeline?

Say one wants to build an API responsible for managing long-running background tasks. A POST might create a job with some associated metadata and a unique identifier, store that somewhere (say, in memory or in a DB), then queue up the job and return the identifier to the client. A GET looks up and returns metadata by key. A DELETE cancels a job if it's still running.

I've considered [FluentScheduler](https://github.com/fluentscheduler), but it doesn't appear to have cancellation support either, and it also doesn't come with queueing or IHostedService baked in. [Hangfire](https://www.hangfire.io/) has [cancellation support](http://docs.hangfire.io/en/latest/background-methods/using-cancellation-tokens.html) along with built-in persistence and a nice dashboard, but I don't like the fact that its [async support](https://github.com/HangfireIO/Hangfire/issues/150) is just nominal; it blocks waiting on tasks to complete. My jobs are long and heavily IO-bound, and I can't really afford for each one to sit on a thread for 3 hours. [It seems real async support is planned, but it's not clear when we might see it](https://github.com/HangfireIO/Hangfire/issues/928).

For now I'm just writing my own background service. But if you do end up adding a feature like this, I'd love to take advantage of it and delete a bunch of custom code :)

In any case, thanks for your work. This is a really useful project.

**Comment by jamesmh** [comment]
Thank for leaving a super detailed explanation 👌

I've had this on my todo as a potential addition - and since you're asking I may move it up in priority 😉

I'll get back to you once I've got something in place 👍

**Comment by jamesmh** [comment]
FYI right now Coravel's processing is using async properly, so it won't hog threads when doing IO.

I'll just need to add the cancellation token as a new ability, which should be easy enough 👌

**Comment by jamesmh** [comment]
Just to chime in as I'm looking at this now.

Are suggesting that Coravel will provide the cancellation token to, let's say, an invocable, so that when the app is closing you want that signal so you can cancel your long running stuff?

Or, do you want control of the cancellation token so you can put some kind of timeout on it etc.?

**Comment by jamesmh** [comment]
So I added a sample project to do this for now. Here are the results of the test just to show you it works:

![image](https://user-images.githubusercontent.com/7213174/51271415-e390fa80-199d-11e9-89a3-54d557035703.png)

Check out` Samples/QueueWithCancellationTokens` under the repo's code.

I'll basically look at integrating something like that into the main code, but for now maybe that helps?

**Comment by jamesmh** [comment]
And... you'll want to remove the tokensource from that concurrent dictionary - right now its leaking :(

**Comment by brianjlacy** [comment]
What's the status on this? Any more progress? I'd really like to be able to reliably cancel a scheduled/queued invocable.

**Comment by jamesmh** [comment]
I was hoping to around to this but I've been busy lately and am taking care of my wife who had major surgery (along with my 8 kids 😯 lol) 

ETA...dunno for sure, but would like to tackle this as the first addition to the project once I get around to it.

**Comment by jamesmh** [comment]
Alright guys, version 3.1.0 has this feature.

https://docs.coravel.net/Queuing/#queuing-an-invocable-that-can-be-cancelled

**Comment by bdaniel7** [comment]
I'm trying to use a cancellable IInvocable, according to the documentation, but Token.IsCancellationRequested is never true, so I can't cancell the job. I'm using Coravel 3.6.1
```
public class MeasuresToReadModelDenormalizer : IInvocable, IDisposable, ICancellableTask
{
    foreach (var measureToDenormalize in measuresToDenormalize)
    {
	    if (Token.IsCancellationRequested)
        {
		    Log.Information(
    		"Cancellation was requested before measure {measureToDenormalizeId}. Will save, then exit.", measureToDenormalize.Id);
	        await commit(dbContext, Token, updatedRecords.ToString());
		    return;
	    }
	...
    }

    /// <inheritdoc />
    public CancellationToken Token { get; set; }
}
```
```
[AuthorizeRoles(Roles.Admin)]
[HttpPost("start-denormalize-measures")]
public IActionResult StartToDenormalizeMeasures()
{
	Guid newGuid = Guid.NewGuid();
	CancellationTokenSource newToken = new CancellationTokenSource();

	tokens.TryAdd(newGuid, newToken);

	queue.QueueCancellableInvocable<MeasuresToReadModelDenormalizer>();

	return new JsonResult(newGuid);
}

[AuthorizeRoles(Roles.Admin)]
[HttpPost("stop-denormalize-measures")]
public IActionResult Stop([FromQuery] Guid guid)
{
	// Make sure we remove and dispose tokens to avoid leaking...
	tokens.TryRemove(guid, out var token);
	token?.Cancel();
	token?.Dispose();
	return new JsonResult("MeasuresToReadModelDenormalizer was cancelled!");
}
```

**Comment by jamesmh** [comment]
You use the feature like this:

```csharp
var token = queue.QueueCancellableInvocable<MeasuresToReadModelDenormalizer>();
// use the token...
```

**Comment by bdaniel7** [comment]
Great! Thank you!

**Comment by jamesmh** [comment]
Np 😊

**Comment by w-bonelli** [comment]
Thanks again @jamesmh 😄 sorry for disappearing

**Comment by itstechtoday** [comment]
We need QueueCancellableInvocableWithPayload as well please.
