### ISSUE TITLE
Invocable lifetime

### ISSUE THREAD

**Issue by soend** [jamesmh/coravel#74]
I would like to call a method in my invocable from a hosted service but it's only possible if i register invocable in transient lifetime. 
In docs invocable is registered:
`services.AddScoped<SendNightlyReportsEmailJob>();`

Will something brake in Coravel internally if i register my invocable as transient? For example:
`services.AddTransient<SendNightlyReportsEmailJob>();`

**Comment by jamesmh** [comment]
You can scope your invocables as transient or scoped and everything should be fine.

If you really wanted (for some reason) you could even create a singleton invocable! That would still work assuming you are injecting dependencies that are appropriate for singletons.

**Comment by soend** [comment]
Thats great, thanks!
