### ISSUE TITLE
System.Reflection.TargetException In Queuing Events

### ISSUE THREAD

**Issue by khabubu** [jamesmh/coravel#80]
**Describe the bug**
I am trying to queue an event with the following line
```
_queue.QueueBroadcast(new PurchaseCreatedEvent(organisation, purchase));
```

When the event is broadcasted the following exception is raised
```
System.Reflection.TargetException
Message : Non-static method requires a target.
StackTrace :    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Coravel.Events.Dispatcher.Broadcast[TEvent](TEvent toBroadcast)
   at Coravel.Queuing.Queue.<>c__DisplayClass10_0`1.<<QueueBroadcast>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Coravel.Tasks.ActionOrAsyncFunc.Invoke()
   at Coravel.Queuing.Queue.InvokeTask(ActionOrAsyncFunc task)
Help Link : 
Source : System.Private.CoreLib
```

**Affected Coravel Feature**
The Coravel Feature is Queuing

**Expected behaviour**
I am expecting that when the queue starts the listeners of the broadcasted event handle the event. I am using Coravel with ASP NET Core 2.1.4

**Comment by jamesmh** [comment]
Thanks for all the details! I've run into this before so I know where it's happening but will need to figure out why....

Could you share the general shape of your `PurchaseCreatedEvent`? (just the method signature)

Also:
- is the `PurchaseCreatedEvent` in the same project as your web or executable project?
- if not, what type of project is it (.NET Standard 2.0?, etc.)

**Comment by khabubu** [comment]
Thank you for the quick replay. The shape of the PurchaseCreatedEvent is
```
public class PurchaseCreatedEvent : IEvent
    {
        public Organisation Organisation { get; set; }

        public Purchase Purchase { get; set; }

        public PurchaseCreatedEvent(Organisation organisation, Purchase purchase)
        {
            Organisation = organisation;
            Purchase = purchase;
        }
    }
```

1. It is in the same project.

**Comment by jamesmh** [comment]
What do your listeners look like? Are they in the same project also?

**Comment by khabubu** [comment]
The listener(s) are in the same project as illustrated below
```
public class PurchaseCreatedListener : IListener<PurchaseCreatedEvent>
    {
        private readonly ApplicationDbContext _context;

        public PurchaseCreatedListener(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task HandleAsync(PurchaseCreatedEvent broadcasted)
        {
            // Ommitted lines for brevity.
        }
    }
```

I am not sure if I have configured events and queues below as show below
```
var provider = app.ApplicationServices;
var registration = provider.ConfigureEvents();
registration.Register<PurchaseCreatedEvent>()
    .Subscribe<PurchaseCreatedListener>();
provider.ConfigureQueue().LogQueuedTaskProgress(provider.GetService<ILogger<IQueue>>())
    .OnError(e => { // Ommited for brevity });
```

I hope I have provide enough information.

**Comment by jamesmh** [comment]
Awesome. I forgot to ask (sorry!) - what version of Coravel are you using?

**Comment by khabubu** [comment]
Version 2.3.1

**Comment by jamesmh** [comment]
Great. I'll try to get to this in the new couple days.

**Comment by jamesmh** [comment]
Quick question: Did you register your listeners with `AddTransient` or `AddScoped`?

**Comment by khabubu** [comment]
No I didn't register with either.  I think that is my issue. Let me try registering it. Ohh is this the proper way to register a listener
```
services.AddTransient<IListener<PurchaseCreatedEvent>, PurchaseCreatedListener>();
```

I had registered the listeners and events as follow
```
var provider = app.ApplicationServices;
var registration = provider.ConfigureEvents();
registration.Register<PurchaseCreatedEvent>()
                .Subscribe<PurchaseCreatedListener>();
```

**Comment by jamesmh** [comment]
You can just do `services.AddTransient<PurchaseCreatedListener>()` - does that fix your issues?

**Comment by khabubu** [comment]
Yes it does. Thank you very much.
PS : I feel stupid now. Thanks again

**Comment by jamesmh** [comment]
hahaha! Don't worry about it. Glad everything is working now 👍
