### ISSUE TITLE
[Question] Any guidance on deploying as a service?

### ISSUE THREAD

**Issue by Jogai** [jamesmh/coravel#85]
This seems a good fit to run in a windows service, but I see no documentation about a scenario like that.

**Comment by jamesmh** [comment]
Def is possible, I should document that scenario specifically.

There is a sample in the code base to run this as an exe, so converting to a service would be the same process as converting any other executable:

https://github.com/jamesmh/coravel/tree/master/Samples/HostBuilderConsole
