### ISSUE TITLE
Coravel Pro dashboard 404

### ISSUE THREAD

**Issue by justusburger** [jamesmh/coravel#93]
**Describe the bug**
After following the instruction outlined on https://www.docs.pro.coravel.net/Installation/ and then browsing to `/Coravel/Dashboard/` simply return 404.

**Affected Coravel Feature**
Coravel Pro

**Expected behaviour**
To see the dashboard

**Comment by justusburger** [comment]
<img width="758" alt="Screenshot 2019-06-15 at 22 03 07" src="https://user-images.githubusercontent.com/4091173/59555851-b0d54780-8fb9-11e9-9520-419753ec48af.png">
<img width="929" alt="Screenshot 2019-06-15 at 22 03 49" src="https://user-images.githubusercontent.com/4091173/59555854-b6cb2880-8fb9-11e9-8c28-70c00452a29a.png">

The route analyser shows nothing I have not registered myself:
<img width="1150" alt="Screenshot 2019-06-15 at 22 07 21" src="https://user-images.githubusercontent.com/4091173/59555873-fbef5a80-8fb9-11e9-84e5-b7ed7ab15dc6.png">

**Comment by jamesmh** [comment]
I'll address the issue on the Coravel Pro repo 👍
