### ISSUE TITLE
Invokable Method Naming

### ISSUE THREAD

**Issue by TechInterMezzo** [jamesmh/coravel#95]
This is more like a formal "problem".

Maybe the Invoke method of IInvocable should be renamed to InvokeAsync?

For example IListener already contains the method HandleAsync with the right suffix for an async method returning a Task.

What do you think? Renaming the method would certainly be a breaking change for the API.

**Comment by jamesmh** [comment]
I agree, but (for now...) I don't like the idea of a breaking change 😥.

**Comment by TechInterMezzo** [comment]
Okay. Should this issue remain open, just for the record?

**Comment by jamesmh** [comment]
I'll close for now, but it's def. in my mind now haahaha 🙃

**Comment by TechInterMezzo** [comment]
Just for the record, the Broadcast method of IDispatcher is also missing an async Suffix. I nearly missed to await it. ;)
