### ISSUE TITLE
Queue Size?

### ISSUE THREAD

**Issue by VictorioBerra** [jamesmh/coravel#97]
I would like to set the max queue size, and I would maybe also like to see how long an item has been queued for. Is this possible?

**Comment by jamesmh** [comment]
Not at the moment. You can set the amount of time it takes for the queue to consume tasks, if that helps in any way -> https://docs.coravel.net/Queuing/#adjusting-the-consummation-delay

**Comment by jamesmh** [comment]
Sry missed this issue...

The functionality is present in current versions. Here are the docs ->[https://docs.coravel.net/Queuing/#metrics](https://docs.coravel.net/Queuing/#metrics)
