### ISSUE TITLE
Mailer: SMTP without authentication

### ISSUE THREAD

**Issue by Dwex** [jamesmh/coravel#99]
**Describe the bug**
My SMTP server uses IP addresses for authentication rather than username and password, so we do not need to authenticate.  When trying to use the MailService without authentication (read as Username and Password not included in the appsettings.json and then also tried listing them as a null, an error returns stating "The SMTP server does not support authentication."

It looks like in the MailServiceRegistration, the authentication criteria is getting populated to an empty string: 
config.GetValue<string>("Coravel:Mail:Username", ""),
config.GetValue<string>("Coravel:Mail:Password", ""),

Then when it gets to the SmtpMailer.cs those fields can't be null so the code won't skip the AuthenticateAsync:
 if (this._username != null && this._password != null){  
     await client.AuthenticateAsync(this._username, this._password); 
}

**Affected Coravel Feature**
Mailer

**Expected behaviour**
I would expect the Mailer to not try to authenticate if no username and password are listed.

**Comment by jamesmh** [comment]
👍 Will look into it.

**Comment by jamesmh** [comment]
Check out version 1.0.2 - should be fixed 👍

**Comment by clipscomb** [comment]
Hey,

I believe this may still be backwards in SmtpMailer.cs:

```
bool useAuth = string.IsNullOrEmpty(this._username) && string.IsNullOrEmpty(this._password);

if (useAuth)
{
    await client.AuthenticateAsync(this._username, this._password);
}
```

If this._username and this._password are both null or empty then useAuth will be true and that would result in calling client.AuthenticateAsync

I think it should be something similar to

```
bool useAuth = !(string.IsNullOrEmpty(this._username) && string.IsNullOrEmpty(this._password));
```

**Comment by jamesmh** [comment]
Of course it is 🤷‍♂️ Sorry guys 🤦‍♂️

**Comment by jamesmh** [comment]
v 1.0.3 should be out soon. See PR above - I added some unit tests this time 🙃

**Comment by Dwex** [comment]
Thanks James
